/*
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.Tag;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * Tag with application timestamp
 */
@Schema(description = "Tag with application timestamp")
@JsonPropertyOrder({
  AppliedTag.JSON_PROPERTY_TAG,
  AppliedTag.JSON_PROPERTY_APPLIED_TIME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class AppliedTag implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TAG = "tag";
  @jakarta.annotation.Nullable  private Tag tag;

  public static final String JSON_PROPERTY_APPLIED_TIME = "applied_time";
  @jakarta.annotation.Nullable  private String appliedTime;

  public AppliedTag() { 
  }

  public AppliedTag tag(@jakarta.annotation.Nullable Tag tag) {
    this.tag = tag;
    return this;
  }

  /**
   * The tag applied
   * @return tag
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The tag applied")
  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Tag getTag() {
    return tag;
  }


  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(@jakarta.annotation.Nullable Tag tag) {
    this.tag = tag;
  }


  public AppliedTag appliedTime(@jakarta.annotation.Nullable String appliedTime) {
    this.appliedTime = appliedTime;
    return this;
  }

  /**
   * The time the tag was applied to the contact, in ISO 8601 format
   * @return appliedTime
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The time the tag was applied to the contact, in ISO 8601 format")
  @JsonProperty(JSON_PROPERTY_APPLIED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAppliedTime() {
    return appliedTime;
  }


  @JsonProperty(JSON_PROPERTY_APPLIED_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppliedTime(@jakarta.annotation.Nullable String appliedTime) {
    this.appliedTime = appliedTime;
  }

  /**
   * Return true if this AppliedTag object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppliedTag appliedTag = (AppliedTag) o;
    return Objects.equals(this.tag, appliedTag.tag) &&
        Objects.equals(this.appliedTime, appliedTag.appliedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, appliedTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppliedTag {\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    appliedTime: ").append(toIndentedString(appliedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private AppliedTag instance;
    
        public Builder() {
          this(new AppliedTag());
        }
    
        protected Builder(AppliedTag instance) {
          this.instance = instance;
        }
    
        public AppliedTag.Builder tag(Tag tag) {
              this.instance.tag = tag;
          return this;
        }
            public AppliedTag.Builder appliedTime(String appliedTime) {
              this.instance.appliedTime = appliedTime;
          return this;
        }
        
    
        /**
        * returns a built AppliedTag instance.
        *
        * The builder is not reusable.
        */
        public AppliedTag build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static AppliedTag.Builder builder() {
        return new AppliedTag.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public AppliedTag.Builder toBuilder() {
        return new AppliedTag.Builder()
          .tag(getTag())
          .appliedTime(getAppliedTime());
      }
}

