/*
 * Keap REST API
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.812056
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.BulkCreateDealNoteResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * Response model for creating multiple deal notes in bulk.
 */
@Schema(description = "Response model for creating multiple deal notes in bulk.")
@JsonPropertyOrder({
  BulkCreateDealNotesResponse.JSON_PROPERTY_CREATE_NOTE_RESPONSES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BulkCreateDealNotesResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CREATE_NOTE_RESPONSES = "create_note_responses";
  @jakarta.annotation.Nullable  private List<@Valid BulkCreateDealNoteResponse> createNoteResponses = new ArrayList<>();

  public BulkCreateDealNotesResponse() { 
  }

  public BulkCreateDealNotesResponse createNoteResponses(@jakarta.annotation.Nullable List<@Valid BulkCreateDealNoteResponse> createNoteResponses) {
    this.createNoteResponses = createNoteResponses;
    return this;
  }

  public BulkCreateDealNotesResponse addCreateNoteResponsesItem(BulkCreateDealNoteResponse createNoteResponsesItem) {
    if (this.createNoteResponses == null) {
      this.createNoteResponses = new ArrayList<>();
    }
    this.createNoteResponses.add(createNoteResponsesItem);
    return this;
  }

  /**
   * List of responses for each deal note creation request. Each response contains details about the creation status and any associated error messages.
   * @return createNoteResponses
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "List of responses for each deal note creation request. Each response contains details about the creation status and any associated error messages.")
  @JsonProperty(JSON_PROPERTY_CREATE_NOTE_RESPONSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid BulkCreateDealNoteResponse> getCreateNoteResponses() {
    return createNoteResponses;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_NOTE_RESPONSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateNoteResponses(@jakarta.annotation.Nullable List<@Valid BulkCreateDealNoteResponse> createNoteResponses) {
    this.createNoteResponses = createNoteResponses;
  }

  /**
   * Return true if this BulkCreateDealNotesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkCreateDealNotesResponse bulkCreateDealNotesResponse = (BulkCreateDealNotesResponse) o;
    return Objects.equals(this.createNoteResponses, bulkCreateDealNotesResponse.createNoteResponses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createNoteResponses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkCreateDealNotesResponse {\n");
    sb.append("    createNoteResponses: ").append(toIndentedString(createNoteResponses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private BulkCreateDealNotesResponse instance;
    
        public Builder() {
          this(new BulkCreateDealNotesResponse());
        }
    
        protected Builder(BulkCreateDealNotesResponse instance) {
          this.instance = instance;
        }
    
        public BulkCreateDealNotesResponse.Builder createNoteResponses(List<BulkCreateDealNoteResponse> createNoteResponses) {
              this.instance.createNoteResponses = createNoteResponses;
          return this;
        }
        
    
        /**
        * returns a built BulkCreateDealNotesResponse instance.
        *
        * The builder is not reusable.
        */
        public BulkCreateDealNotesResponse build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static BulkCreateDealNotesResponse.Builder builder() {
        return new BulkCreateDealNotesResponse.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public BulkCreateDealNotesResponse.Builder toBuilder() {
        return new BulkCreateDealNotesResponse.Builder()
          .createNoteResponses(getCreateNoteResponses());
      }
}

