/*
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * task
 */
@Schema(description = "task")
@JsonPropertyOrder({
  CreateTaskRequest.JSON_PROPERTY_TITLE,
  CreateTaskRequest.JSON_PROPERTY_DESCRIPTION,
  CreateTaskRequest.JSON_PROPERTY_TYPE,
  CreateTaskRequest.JSON_PROPERTY_PRIORITY,
  CreateTaskRequest.JSON_PROPERTY_COMPLETED,
  CreateTaskRequest.JSON_PROPERTY_COMPLETION_TIME,
  CreateTaskRequest.JSON_PROPERTY_DUE_TIME,
  CreateTaskRequest.JSON_PROPERTY_REMIND_TIME_MINS,
  CreateTaskRequest.JSON_PROPERTY_ASSIGNED_TO_USER_ID,
  CreateTaskRequest.JSON_PROPERTY_CONTACT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateTaskRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable  private String description;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable  private String type;

  /**
   * Task priority
   */
  public enum PriorityEnum {
    CRITICAL(String.valueOf("CRITICAL")),
    
    ESSENTIAL(String.valueOf("ESSENTIAL")),
    
    NONESSENTIAL(String.valueOf("NONESSENTIAL")),
    
    UNKNOWN_COULD_NOT_DESERIALIZE(String.valueOf("unknown_default_open_api"));

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PriorityEnum fromValue(String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_COULD_NOT_DESERIALIZE;
    }
  }
  public static final String JSON_PROPERTY_PRIORITY = "priority";
  @jakarta.annotation.Nullable  private PriorityEnum priority;

  public static final String JSON_PROPERTY_COMPLETED = "completed";
  @jakarta.annotation.Nullable  private Boolean completed;

  public static final String JSON_PROPERTY_COMPLETION_TIME = "completion_time";
  @jakarta.annotation.Nullable  private String completionTime;

  public static final String JSON_PROPERTY_DUE_TIME = "due_time";
  @jakarta.annotation.Nullable  private String dueTime;

  /**
   * Value in minutes before start_date to show pop-up reminder.
   */
  public enum RemindTimeMinsEnum {
    NUMBER_5(Integer.valueOf(5)),
    
    NUMBER_10(Integer.valueOf(10)),
    
    NUMBER_15(Integer.valueOf(15)),
    
    NUMBER_30(Integer.valueOf(30)),
    
    NUMBER_60(Integer.valueOf(60)),
    
    NUMBER_120(Integer.valueOf(120)),
    
    NUMBER_240(Integer.valueOf(240)),
    
    NUMBER_480(Integer.valueOf(480)),
    
    NUMBER_1440(Integer.valueOf(1440)),
    
    NUMBER_2880(Integer.valueOf(2880)),
    
    UNKNOWN_COULD_NOT_DESERIALIZE(Integer.valueOf(11184809));

    private Integer value;

    RemindTimeMinsEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RemindTimeMinsEnum fromValue(Integer value) {
      for (RemindTimeMinsEnum b : RemindTimeMinsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_COULD_NOT_DESERIALIZE;
    }
  }
  public static final String JSON_PROPERTY_REMIND_TIME_MINS = "remind_time_mins";
  @jakarta.annotation.Nullable  private RemindTimeMinsEnum remindTimeMins;

  public static final String JSON_PROPERTY_ASSIGNED_TO_USER_ID = "assigned_to_user_id";
  @jakarta.annotation.Nonnull  private String assignedToUserId;

  public static final String JSON_PROPERTY_CONTACT_ID = "contact_id";
  @jakarta.annotation.Nullable  private String contactId;

  public CreateTaskRequest() { 
  }

  public CreateTaskRequest title(@jakarta.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Task title
   * @return title
   */
  @jakarta.annotation.Nullable  @Schema(example = "Follow up on proposal", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Task title")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }


  public CreateTaskRequest description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Task description
   * @return description
   */
  @jakarta.annotation.Nullable  @Schema(example = "Review client feedback", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Task description")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateTaskRequest type(@jakarta.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Task type
   * @return type
   */
  @jakarta.annotation.Nullable  @Schema(example = "CALL", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Task type")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }


  public CreateTaskRequest priority(@jakarta.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Task priority
   * @return priority
   */
  @jakarta.annotation.Nullable  @Schema(example = "ESSENTIAL", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Task priority")
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PriorityEnum getPriority() {
    return priority;
  }


  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(@jakarta.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
  }


  public CreateTaskRequest completed(@jakarta.annotation.Nullable Boolean completed) {
    this.completed = completed;
    return this;
  }

  /**
   * Whether task is completed
   * @return completed
   */
  @jakarta.annotation.Nullable  @Schema(example = "false", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Whether task is completed")
  @JsonProperty(JSON_PROPERTY_COMPLETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCompleted() {
    return completed;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompleted(@jakarta.annotation.Nullable Boolean completed) {
    this.completed = completed;
  }


  public CreateTaskRequest completionTime(@jakarta.annotation.Nullable String completionTime) {
    this.completionTime = completionTime;
    return this;
  }

  /**
   * Completion timestamp (ISO-8601)
   * @return completionTime
   */
  @jakarta.annotation.Nullable  @Schema(example = "2024-03-20T14:00:00Z", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Completion timestamp (ISO-8601)")
  @JsonProperty(JSON_PROPERTY_COMPLETION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCompletionTime() {
    return completionTime;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompletionTime(@jakarta.annotation.Nullable String completionTime) {
    this.completionTime = completionTime;
  }


  public CreateTaskRequest dueTime(@jakarta.annotation.Nullable String dueTime) {
    this.dueTime = dueTime;
    return this;
  }

  /**
   * Due date/time (ISO-8601)
   * @return dueTime
   */
  @jakarta.annotation.Nullable  @Schema(example = "2024-03-18T17:00:00Z", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Due date/time (ISO-8601)")
  @JsonProperty(JSON_PROPERTY_DUE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDueTime() {
    return dueTime;
  }


  @JsonProperty(JSON_PROPERTY_DUE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDueTime(@jakarta.annotation.Nullable String dueTime) {
    this.dueTime = dueTime;
  }


  public CreateTaskRequest remindTimeMins(@jakarta.annotation.Nullable RemindTimeMinsEnum remindTimeMins) {
    this.remindTimeMins = remindTimeMins;
    return this;
  }

  /**
   * Value in minutes before start_date to show pop-up reminder.
   * @return remindTimeMins
   */
  @jakarta.annotation.Nullable  @Schema(example = "30", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Value in minutes before start_date to show pop-up reminder.")
  @JsonProperty(JSON_PROPERTY_REMIND_TIME_MINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RemindTimeMinsEnum getRemindTimeMins() {
    return remindTimeMins;
  }


  @JsonProperty(JSON_PROPERTY_REMIND_TIME_MINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemindTimeMins(@jakarta.annotation.Nullable RemindTimeMinsEnum remindTimeMins) {
    this.remindTimeMins = remindTimeMins;
  }


  public CreateTaskRequest assignedToUserId(@jakarta.annotation.Nonnull String assignedToUserId) {
    this.assignedToUserId = assignedToUserId;
    return this;
  }

  /**
   * Assigned user ID
   * @return assignedToUserId
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(example = "456", requiredMode = Schema.RequiredMode.REQUIRED, description = "Assigned user ID")
  @JsonProperty(JSON_PROPERTY_ASSIGNED_TO_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAssignedToUserId() {
    return assignedToUserId;
  }


  @JsonProperty(JSON_PROPERTY_ASSIGNED_TO_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssignedToUserId(@jakarta.annotation.Nonnull String assignedToUserId) {
    this.assignedToUserId = assignedToUserId;
  }


  public CreateTaskRequest contactId(@jakarta.annotation.Nullable String contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * Associated contact ID
   * @return contactId
   */
  @jakarta.annotation.Nullable  @Schema(example = "1001", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Associated contact ID")
  @JsonProperty(JSON_PROPERTY_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContactId() {
    return contactId;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactId(@jakarta.annotation.Nullable String contactId) {
    this.contactId = contactId;
  }

  /**
   * Return true if this CreateTaskRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTaskRequest createTaskRequest = (CreateTaskRequest) o;
    return Objects.equals(this.title, createTaskRequest.title) &&
        Objects.equals(this.description, createTaskRequest.description) &&
        Objects.equals(this.type, createTaskRequest.type) &&
        Objects.equals(this.priority, createTaskRequest.priority) &&
        Objects.equals(this.completed, createTaskRequest.completed) &&
        Objects.equals(this.completionTime, createTaskRequest.completionTime) &&
        Objects.equals(this.dueTime, createTaskRequest.dueTime) &&
        Objects.equals(this.remindTimeMins, createTaskRequest.remindTimeMins) &&
        Objects.equals(this.assignedToUserId, createTaskRequest.assignedToUserId) &&
        Objects.equals(this.contactId, createTaskRequest.contactId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, type, priority, completed, completionTime, dueTime, remindTimeMins, assignedToUserId, contactId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTaskRequest {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    completionTime: ").append(toIndentedString(completionTime)).append("\n");
    sb.append("    dueTime: ").append(toIndentedString(dueTime)).append("\n");
    sb.append("    remindTimeMins: ").append(toIndentedString(remindTimeMins)).append("\n");
    sb.append("    assignedToUserId: ").append(toIndentedString(assignedToUserId)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private CreateTaskRequest instance;
    
        public Builder() {
          this(new CreateTaskRequest());
        }
    
        protected Builder(CreateTaskRequest instance) {
          this.instance = instance;
        }
    
        public CreateTaskRequest.Builder title(String title) {
              this.instance.title = title;
          return this;
        }
            public CreateTaskRequest.Builder description(String description) {
              this.instance.description = description;
          return this;
        }
            public CreateTaskRequest.Builder type(String type) {
              this.instance.type = type;
          return this;
        }
            public CreateTaskRequest.Builder priority(PriorityEnum priority) {
              this.instance.priority = priority;
          return this;
        }
            public CreateTaskRequest.Builder completed(Boolean completed) {
              this.instance.completed = completed;
          return this;
        }
            public CreateTaskRequest.Builder completionTime(String completionTime) {
              this.instance.completionTime = completionTime;
          return this;
        }
            public CreateTaskRequest.Builder dueTime(String dueTime) {
              this.instance.dueTime = dueTime;
          return this;
        }
            public CreateTaskRequest.Builder remindTimeMins(RemindTimeMinsEnum remindTimeMins) {
              this.instance.remindTimeMins = remindTimeMins;
          return this;
        }
            public CreateTaskRequest.Builder assignedToUserId(String assignedToUserId) {
              this.instance.assignedToUserId = assignedToUserId;
          return this;
        }
            public CreateTaskRequest.Builder contactId(String contactId) {
              this.instance.contactId = contactId;
          return this;
        }
        
    
        /**
        * returns a built CreateTaskRequest instance.
        *
        * The builder is not reusable.
        */
        public CreateTaskRequest build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static CreateTaskRequest.Builder builder() {
        return new CreateTaskRequest.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public CreateTaskRequest.Builder toBuilder() {
        return new CreateTaskRequest.Builder()
          .title(getTitle())
          .description(getDescription())
          .type(getType())
          .priority(getPriority())
          .completed(getCompleted())
          .completionTime(getCompletionTime())
          .dueTime(getDueTime())
          .remindTimeMins(getRemindTimeMins())
          .assignedToUserId(getAssignedToUserId())
          .contactId(getContactId());
      }
}

