/*
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.FlowEventResultDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * Result of achieving a specific goal
 */
@Schema(description = "Result of achieving a specific goal")
@JsonPropertyOrder({
  GoalEventResultDTO.JSON_PROPERTY_SUCCESS,
  GoalEventResultDTO.JSON_PROPERTY_MESSAGE,
  GoalEventResultDTO.JSON_PROPERTY_AUTOMATION_ID,
  GoalEventResultDTO.JSON_PROPERTY_GOAL_ID,
  GoalEventResultDTO.JSON_PROPERTY_FLOW_START_RESULTS,
  GoalEventResultDTO.JSON_PROPERTY_FLOW_STOP_RESULTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class GoalEventResultDTO implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SUCCESS = "success";
  @jakarta.annotation.Nullable  private Boolean success;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable  private String message;

  public static final String JSON_PROPERTY_AUTOMATION_ID = "automation_id";
  @jakarta.annotation.Nullable  private Long automationId;

  public static final String JSON_PROPERTY_GOAL_ID = "goal_id";
  @jakarta.annotation.Nullable  private Long goalId;

  public static final String JSON_PROPERTY_FLOW_START_RESULTS = "flow_start_results";
  @jakarta.annotation.Nullable  private List<@Valid FlowEventResultDTO> flowStartResults = new ArrayList<>();

  public static final String JSON_PROPERTY_FLOW_STOP_RESULTS = "flow_stop_results";
  @jakarta.annotation.Nullable  private List<@Valid FlowEventResultDTO> flowStopResults = new ArrayList<>();

  public GoalEventResultDTO() { 
  }

  public GoalEventResultDTO success(@jakarta.annotation.Nullable Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Whether the goal was successfully achieved
   * @return success
   */
  @jakarta.annotation.Nullable  @Schema(example = "true", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Whether the goal was successfully achieved")
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(@jakarta.annotation.Nullable Boolean success) {
    this.success = success;
  }


  public GoalEventResultDTO message(@jakarta.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * A message with details about the result
   * @return message
   */
  @jakarta.annotation.Nullable  @Schema(example = "Goal achieved successfully", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "A message with details about the result")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public GoalEventResultDTO automationId(@jakarta.annotation.Nullable Long automationId) {
    this.automationId = automationId;
    return this;
  }

  /**
   * The automation ID where the goal was achieved
   * @return automationId
   */
  @jakarta.annotation.Nullable  @Schema(example = "123", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The automation ID where the goal was achieved")
  @JsonProperty(JSON_PROPERTY_AUTOMATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getAutomationId() {
    return automationId;
  }


  @JsonProperty(JSON_PROPERTY_AUTOMATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutomationId(@jakarta.annotation.Nullable Long automationId) {
    this.automationId = automationId;
  }


  public GoalEventResultDTO goalId(@jakarta.annotation.Nullable Long goalId) {
    this.goalId = goalId;
    return this;
  }

  /**
   * The goal ID that was achieved
   * @return goalId
   */
  @jakarta.annotation.Nullable  @Schema(example = "456", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The goal ID that was achieved")
  @JsonProperty(JSON_PROPERTY_GOAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getGoalId() {
    return goalId;
  }


  @JsonProperty(JSON_PROPERTY_GOAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoalId(@jakarta.annotation.Nullable Long goalId) {
    this.goalId = goalId;
  }


  public GoalEventResultDTO flowStartResults(@jakarta.annotation.Nullable List<@Valid FlowEventResultDTO> flowStartResults) {
    this.flowStartResults = flowStartResults;
    return this;
  }

  public GoalEventResultDTO addFlowStartResultsItem(FlowEventResultDTO flowStartResultsItem) {
    if (this.flowStartResults == null) {
      this.flowStartResults = new ArrayList<>();
    }
    this.flowStartResults.add(flowStartResultsItem);
    return this;
  }

  /**
   * List of flows that were started as a result of achieving this goal
   * @return flowStartResults
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "List of flows that were started as a result of achieving this goal")
  @JsonProperty(JSON_PROPERTY_FLOW_START_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid FlowEventResultDTO> getFlowStartResults() {
    return flowStartResults;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_START_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowStartResults(@jakarta.annotation.Nullable List<@Valid FlowEventResultDTO> flowStartResults) {
    this.flowStartResults = flowStartResults;
  }


  public GoalEventResultDTO flowStopResults(@jakarta.annotation.Nullable List<@Valid FlowEventResultDTO> flowStopResults) {
    this.flowStopResults = flowStopResults;
    return this;
  }

  public GoalEventResultDTO addFlowStopResultsItem(FlowEventResultDTO flowStopResultsItem) {
    if (this.flowStopResults == null) {
      this.flowStopResults = new ArrayList<>();
    }
    this.flowStopResults.add(flowStopResultsItem);
    return this;
  }

  /**
   * List of flows that were stopped as a result of achieving this goal
   * @return flowStopResults
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "List of flows that were stopped as a result of achieving this goal")
  @JsonProperty(JSON_PROPERTY_FLOW_STOP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid FlowEventResultDTO> getFlowStopResults() {
    return flowStopResults;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_STOP_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowStopResults(@jakarta.annotation.Nullable List<@Valid FlowEventResultDTO> flowStopResults) {
    this.flowStopResults = flowStopResults;
  }

  /**
   * Return true if this GoalEventResultDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoalEventResultDTO goalEventResultDTO = (GoalEventResultDTO) o;
    return Objects.equals(this.success, goalEventResultDTO.success) &&
        Objects.equals(this.message, goalEventResultDTO.message) &&
        Objects.equals(this.automationId, goalEventResultDTO.automationId) &&
        Objects.equals(this.goalId, goalEventResultDTO.goalId) &&
        Objects.equals(this.flowStartResults, goalEventResultDTO.flowStartResults) &&
        Objects.equals(this.flowStopResults, goalEventResultDTO.flowStopResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, message, automationId, goalId, flowStartResults, flowStopResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoalEventResultDTO {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    automationId: ").append(toIndentedString(automationId)).append("\n");
    sb.append("    goalId: ").append(toIndentedString(goalId)).append("\n");
    sb.append("    flowStartResults: ").append(toIndentedString(flowStartResults)).append("\n");
    sb.append("    flowStopResults: ").append(toIndentedString(flowStopResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private GoalEventResultDTO instance;
    
        public Builder() {
          this(new GoalEventResultDTO());
        }
    
        protected Builder(GoalEventResultDTO instance) {
          this.instance = instance;
        }
    
        public GoalEventResultDTO.Builder success(Boolean success) {
              this.instance.success = success;
          return this;
        }
            public GoalEventResultDTO.Builder message(String message) {
              this.instance.message = message;
          return this;
        }
            public GoalEventResultDTO.Builder automationId(Long automationId) {
              this.instance.automationId = automationId;
          return this;
        }
            public GoalEventResultDTO.Builder goalId(Long goalId) {
              this.instance.goalId = goalId;
          return this;
        }
            public GoalEventResultDTO.Builder flowStartResults(List<FlowEventResultDTO> flowStartResults) {
              this.instance.flowStartResults = flowStartResults;
          return this;
        }
            public GoalEventResultDTO.Builder flowStopResults(List<FlowEventResultDTO> flowStopResults) {
              this.instance.flowStopResults = flowStopResults;
          return this;
        }
        
    
        /**
        * returns a built GoalEventResultDTO instance.
        *
        * The builder is not reusable.
        */
        public GoalEventResultDTO build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static GoalEventResultDTO.Builder builder() {
        return new GoalEventResultDTO.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public GoalEventResultDTO.Builder toBuilder() {
        return new GoalEventResultDTO.Builder()
          .success(getSuccess())
          .message(getMessage())
          .automationId(getAutomationId())
          .goalId(getGoalId())
          .flowStartResults(getFlowStartResults())
          .flowStopResults(getFlowStopResults());
      }
}

