/*
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.SubscriptionList;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * ListSubscriptionsResponseList
 */
@JsonPropertyOrder({
  ListSubscriptionsResponseList.JSON_PROPERTY_SUBSCRIPTIONS,
  ListSubscriptionsResponseList.JSON_PROPERTY_NEXT_PAGE_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ListSubscriptionsResponseList implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SUBSCRIPTIONS = "subscriptions";
  @jakarta.annotation.Nullable  private List<@Valid SubscriptionList> subscriptions = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_PAGE_TOKEN = "next_page_token";
  @jakarta.annotation.Nullable  private String nextPageToken;

  public ListSubscriptionsResponseList() { 
  }

  public ListSubscriptionsResponseList subscriptions(@jakarta.annotation.Nullable List<@Valid SubscriptionList> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public ListSubscriptionsResponseList addSubscriptionsItem(SubscriptionList subscriptionsItem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<>();
    }
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

  /**
   * Get subscriptions
   * @return subscriptions
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid SubscriptionList> getSubscriptions() {
    return subscriptions;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscriptions(@jakarta.annotation.Nullable List<@Valid SubscriptionList> subscriptions) {
    this.subscriptions = subscriptions;
  }


  public ListSubscriptionsResponseList nextPageToken(@jakarta.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * Get nextPageToken
   * @return nextPageToken
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNextPageToken() {
    return nextPageToken;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextPageToken(@jakarta.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }

  /**
   * Return true if this ListSubscriptionsResponse_List object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSubscriptionsResponseList listSubscriptionsResponseList = (ListSubscriptionsResponseList) o;
    return Objects.equals(this.subscriptions, listSubscriptionsResponseList.subscriptions) &&
        Objects.equals(this.nextPageToken, listSubscriptionsResponseList.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptions, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSubscriptionsResponseList {\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private ListSubscriptionsResponseList instance;
    
        public Builder() {
          this(new ListSubscriptionsResponseList());
        }
    
        protected Builder(ListSubscriptionsResponseList instance) {
          this.instance = instance;
        }
    
        public ListSubscriptionsResponseList.Builder subscriptions(List<SubscriptionList> subscriptions) {
              this.instance.subscriptions = subscriptions;
          return this;
        }
            public ListSubscriptionsResponseList.Builder nextPageToken(String nextPageToken) {
              this.instance.nextPageToken = nextPageToken;
          return this;
        }
        
    
        /**
        * returns a built ListSubscriptionsResponseList instance.
        *
        * The builder is not reusable.
        */
        public ListSubscriptionsResponseList build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static ListSubscriptionsResponseList.Builder builder() {
        return new ListSubscriptionsResponseList.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public ListSubscriptionsResponseList.Builder toBuilder() {
        return new ListSubscriptionsResponseList.Builder()
          .subscriptions(getSubscriptions())
          .nextPageToken(getNextPageToken());
      }
}

