/*
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.PaymentMethod;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * Payment
 */
@JsonPropertyOrder({
  Payment.JSON_PROPERTY_ID,
  Payment.JSON_PROPERTY_TYPE,
  Payment.JSON_PROPERTY_AMOUNT,
  Payment.JSON_PROPERTY_NOTE,
  Payment.JSON_PROPERTY_STATUS,
  Payment.JSON_PROPERTY_COMMISSIONED,
  Payment.JSON_PROPERTY_SYNCED,
  Payment.JSON_PROPERTY_PAYMENT_TIME,
  Payment.JSON_PROPERTY_REFUND_PAYMENT_ID,
  Payment.JSON_PROPERTY_CONTACT_ID,
  Payment.JSON_PROPERTY_ORDER_IDS,
  Payment.JSON_PROPERTY_UPDATE_TIME,
  Payment.JSON_PROPERTY_EXTERNAL_TRANSACTION_ID,
  Payment.JSON_PROPERTY_MERCHANT_ACCOUNT_ID,
  Payment.JSON_PROPERTY_MERCHANT_ACCOUNT_TYPE,
  Payment.JSON_PROPERTY_PAYMENT_METHOD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Payment implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable  private String type;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nullable  private Double amount;

  public static final String JSON_PROPERTY_NOTE = "note";
  @jakarta.annotation.Nullable  private String note;

  /**
   * Provides the current status of the payment, if available.
   */
  public enum StatusEnum {
    PENDING(String.valueOf("PENDING")),
    
    APPROVED(String.valueOf("APPROVED")),
    
    COMPLETED(String.valueOf("COMPLETED")),
    
    NONE(String.valueOf("NONE")),
    
    UNKNOWN_COULD_NOT_DESERIALIZE(String.valueOf("unknown_default_open_api"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_COULD_NOT_DESERIALIZE;
    }
  }
  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable  private StatusEnum status;

  public static final String JSON_PROPERTY_COMMISSIONED = "commissioned";
  @jakarta.annotation.Nullable  private Boolean commissioned;

  public static final String JSON_PROPERTY_SYNCED = "synced";
  @jakarta.annotation.Nullable  private Boolean synced;

  public static final String JSON_PROPERTY_PAYMENT_TIME = "payment_time";
  @jakarta.annotation.Nullable  private ZonedDateTime paymentTime;

  public static final String JSON_PROPERTY_REFUND_PAYMENT_ID = "refund_payment_id";
  @jakarta.annotation.Nullable  private String refundPaymentId;

  public static final String JSON_PROPERTY_CONTACT_ID = "contact_id";
  @jakarta.annotation.Nullable  private String contactId;

  public static final String JSON_PROPERTY_ORDER_IDS = "order_ids";
  @jakarta.annotation.Nullable  private List<String> orderIds = new ArrayList<>();

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  @jakarta.annotation.Nullable  private ZonedDateTime updateTime;

  public static final String JSON_PROPERTY_EXTERNAL_TRANSACTION_ID = "external_transaction_id";
  @jakarta.annotation.Nullable  private String externalTransactionId;

  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT_ID = "merchant_account_id";
  @jakarta.annotation.Nullable  private String merchantAccountId;

  /**
   * The merchant account type through which the transaction was made.
   */
  public enum MerchantAccountTypeEnum {
    PAYPAL(String.valueOf("PAYPAL")),
    
    UNSUPPORTED(String.valueOf("UNSUPPORTED")),
    
    AUTHORIZE(String.valueOf("AUTHORIZE")),
    
    EWAY(String.valueOf("EWAY")),
    
    WEPAY(String.valueOf("WEPAY")),
    
    STRIPE(String.valueOf("STRIPE")),
    
    KEAP_PAY(String.valueOf("KEAP_PAY")),
    
    UNKNOWN_COULD_NOT_DESERIALIZE(String.valueOf("unknown_default_open_api"));

    private String value;

    MerchantAccountTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MerchantAccountTypeEnum fromValue(String value) {
      for (MerchantAccountTypeEnum b : MerchantAccountTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_COULD_NOT_DESERIALIZE;
    }
  }
  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT_TYPE = "merchant_account_type";
  @jakarta.annotation.Nullable  private MerchantAccountTypeEnum merchantAccountType;

  public static final String JSON_PROPERTY_PAYMENT_METHOD = "payment_method";
  @jakarta.annotation.Nullable  private PaymentMethod paymentMethod;

  public Payment() { 
  }

  public Payment id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of the payment.
   * @return id
   */
  @jakarta.annotation.Nullable  @Schema(example = "123", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The unique identifier of the payment.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public Payment type(@jakarta.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * A label describing the type of payment made.
   * @return type
   */
  @jakarta.annotation.Nullable  @Schema(example = "Credit Card", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "A label describing the type of payment made.")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }


  public Payment amount(@jakarta.annotation.Nullable Double amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The payment amount.
   * @return amount
   */
  @jakarta.annotation.Nullable  @Schema(example = "123.34", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The payment amount.")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(@jakarta.annotation.Nullable Double amount) {
    this.amount = amount;
  }


  public Payment note(@jakarta.annotation.Nullable String note) {
    this.note = note;
    return this;
  }

  /**
   * A note about the payment.
   * @return note
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "A note about the payment.")
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNote(@jakarta.annotation.Nullable String note) {
    this.note = note;
  }


  public Payment status(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Provides the current status of the payment, if available.
   * @return status
   */
  @jakarta.annotation.Nullable  @Schema(example = "COMPLETED", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Provides the current status of the payment, if available.")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public Payment commissioned(@jakarta.annotation.Nullable Boolean commissioned) {
    this.commissioned = commissioned;
    return this;
  }

  /**
   * Whether this payment had a commission.
   * @return commissioned
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Whether this payment had a commission.")
  @JsonProperty(JSON_PROPERTY_COMMISSIONED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCommissioned() {
    return commissioned;
  }


  @JsonProperty(JSON_PROPERTY_COMMISSIONED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommissioned(@jakarta.annotation.Nullable Boolean commissioned) {
    this.commissioned = commissioned;
  }


  public Payment synced(@jakarta.annotation.Nullable Boolean synced) {
    this.synced = synced;
    return this;
  }

  /**
   * Whether or not the data is synced externally.
   * @return synced
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Whether or not the data is synced externally.")
  @JsonProperty(JSON_PROPERTY_SYNCED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSynced() {
    return synced;
  }


  @JsonProperty(JSON_PROPERTY_SYNCED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSynced(@jakarta.annotation.Nullable Boolean synced) {
    this.synced = synced;
  }


  public Payment paymentTime(@jakarta.annotation.Nullable ZonedDateTime paymentTime) {
    this.paymentTime = paymentTime;
    return this;
  }

  /**
   * When this payment was made. In ISO-8601 format.
   * @return paymentTime
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(example = "2024-05-21T14:30:00Z", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "When this payment was made. In ISO-8601 format.")
  @JsonProperty(JSON_PROPERTY_PAYMENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ZonedDateTime getPaymentTime() {
    return paymentTime;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentTime(@jakarta.annotation.Nullable ZonedDateTime paymentTime) {
    this.paymentTime = paymentTime;
  }


  public Payment refundPaymentId(@jakarta.annotation.Nullable String refundPaymentId) {
    this.refundPaymentId = refundPaymentId;
    return this;
  }

  /**
   * If this payment had a refund, this refers to the id of the refund payment.
   * @return refundPaymentId
   */
  @jakarta.annotation.Nullable  @Schema(example = "123", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "If this payment had a refund, this refers to the id of the refund payment.")
  @JsonProperty(JSON_PROPERTY_REFUND_PAYMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRefundPaymentId() {
    return refundPaymentId;
  }


  @JsonProperty(JSON_PROPERTY_REFUND_PAYMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundPaymentId(@jakarta.annotation.Nullable String refundPaymentId) {
    this.refundPaymentId = refundPaymentId;
  }


  public Payment contactId(@jakarta.annotation.Nullable String contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * The id of the contact the payment is associated with.
   * @return contactId
   */
  @jakarta.annotation.Nullable  @Schema(example = "123", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The id of the contact the payment is associated with.")
  @JsonProperty(JSON_PROPERTY_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContactId() {
    return contactId;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactId(@jakarta.annotation.Nullable String contactId) {
    this.contactId = contactId;
  }


  public Payment orderIds(@jakarta.annotation.Nullable List<String> orderIds) {
    this.orderIds = orderIds;
    return this;
  }

  public Payment addOrderIdsItem(String orderIdsItem) {
    if (this.orderIds == null) {
      this.orderIds = new ArrayList<>();
    }
    this.orderIds.add(orderIdsItem);
    return this;
  }

  /**
   * List of order ids the payment was made was against.
   * @return orderIds
   */
  @jakarta.annotation.Nullable  @Schema(example = "[123, 456]", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "List of order ids the payment was made was against.")
  @JsonProperty(JSON_PROPERTY_ORDER_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getOrderIds() {
    return orderIds;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderIds(@jakarta.annotation.Nullable List<String> orderIds) {
    this.orderIds = orderIds;
  }


  public Payment updateTime(@jakarta.annotation.Nullable ZonedDateTime updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * When this payment was updated. In ISO-8601 format.
   * @return updateTime
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(example = "2024-05-21T14:30:00Z", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "When this payment was updated. In ISO-8601 format.")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ZonedDateTime getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable ZonedDateTime updateTime) {
    this.updateTime = updateTime;
  }


  public Payment externalTransactionId(@jakarta.annotation.Nullable String externalTransactionId) {
    this.externalTransactionId = externalTransactionId;
    return this;
  }

  /**
   * An external id - typically from a payment processor - that references this transaction.
   * @return externalTransactionId
   */
  @jakarta.annotation.Nullable  @Schema(example = "txn_123", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "An external id - typically from a payment processor - that references this transaction.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExternalTransactionId() {
    return externalTransactionId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalTransactionId(@jakarta.annotation.Nullable String externalTransactionId) {
    this.externalTransactionId = externalTransactionId;
  }


  public Payment merchantAccountId(@jakarta.annotation.Nullable String merchantAccountId) {
    this.merchantAccountId = merchantAccountId;
    return this;
  }

  /**
   * The merchant account id through which the transaction was made.
   * @return merchantAccountId
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The merchant account id through which the transaction was made.")
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMerchantAccountId() {
    return merchantAccountId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAccountId(@jakarta.annotation.Nullable String merchantAccountId) {
    this.merchantAccountId = merchantAccountId;
  }


  public Payment merchantAccountType(@jakarta.annotation.Nullable MerchantAccountTypeEnum merchantAccountType) {
    this.merchantAccountType = merchantAccountType;
    return this;
  }

  /**
   * The merchant account type through which the transaction was made.
   * @return merchantAccountType
   */
  @jakarta.annotation.Nullable  @Schema(example = "PAYPAL", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The merchant account type through which the transaction was made.")
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MerchantAccountTypeEnum getMerchantAccountType() {
    return merchantAccountType;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAccountType(@jakarta.annotation.Nullable MerchantAccountTypeEnum merchantAccountType) {
    this.merchantAccountType = merchantAccountType;
  }


  public Payment paymentMethod(@jakarta.annotation.Nullable PaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  /**
   * Details of the payment method used for this transaction.
   * @return paymentMethod
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Details of the payment method used for this transaction.")
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaymentMethod getPaymentMethod() {
    return paymentMethod;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentMethod(@jakarta.annotation.Nullable PaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  /**
   * Return true if this Payment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.id, payment.id) &&
        Objects.equals(this.type, payment.type) &&
        Objects.equals(this.amount, payment.amount) &&
        Objects.equals(this.note, payment.note) &&
        Objects.equals(this.status, payment.status) &&
        Objects.equals(this.commissioned, payment.commissioned) &&
        Objects.equals(this.synced, payment.synced) &&
        Objects.equals(this.paymentTime, payment.paymentTime) &&
        Objects.equals(this.refundPaymentId, payment.refundPaymentId) &&
        Objects.equals(this.contactId, payment.contactId) &&
        Objects.equals(this.orderIds, payment.orderIds) &&
        Objects.equals(this.updateTime, payment.updateTime) &&
        Objects.equals(this.externalTransactionId, payment.externalTransactionId) &&
        Objects.equals(this.merchantAccountId, payment.merchantAccountId) &&
        Objects.equals(this.merchantAccountType, payment.merchantAccountType) &&
        Objects.equals(this.paymentMethod, payment.paymentMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, amount, note, status, commissioned, synced, paymentTime, refundPaymentId, contactId, orderIds, updateTime, externalTransactionId, merchantAccountId, merchantAccountType, paymentMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    commissioned: ").append(toIndentedString(commissioned)).append("\n");
    sb.append("    synced: ").append(toIndentedString(synced)).append("\n");
    sb.append("    paymentTime: ").append(toIndentedString(paymentTime)).append("\n");
    sb.append("    refundPaymentId: ").append(toIndentedString(refundPaymentId)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    orderIds: ").append(toIndentedString(orderIds)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    externalTransactionId: ").append(toIndentedString(externalTransactionId)).append("\n");
    sb.append("    merchantAccountId: ").append(toIndentedString(merchantAccountId)).append("\n");
    sb.append("    merchantAccountType: ").append(toIndentedString(merchantAccountType)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private Payment instance;
    
        public Builder() {
          this(new Payment());
        }
    
        protected Builder(Payment instance) {
          this.instance = instance;
        }
    
        public Payment.Builder id(String id) {
              this.instance.id = id;
          return this;
        }
            public Payment.Builder type(String type) {
              this.instance.type = type;
          return this;
        }
            public Payment.Builder amount(Double amount) {
              this.instance.amount = amount;
          return this;
        }
            public Payment.Builder note(String note) {
              this.instance.note = note;
          return this;
        }
            public Payment.Builder status(StatusEnum status) {
              this.instance.status = status;
          return this;
        }
            public Payment.Builder commissioned(Boolean commissioned) {
              this.instance.commissioned = commissioned;
          return this;
        }
            public Payment.Builder synced(Boolean synced) {
              this.instance.synced = synced;
          return this;
        }
            public Payment.Builder paymentTime(ZonedDateTime paymentTime) {
              this.instance.paymentTime = paymentTime;
          return this;
        }
            public Payment.Builder refundPaymentId(String refundPaymentId) {
              this.instance.refundPaymentId = refundPaymentId;
          return this;
        }
            public Payment.Builder contactId(String contactId) {
              this.instance.contactId = contactId;
          return this;
        }
            public Payment.Builder orderIds(List<String> orderIds) {
              this.instance.orderIds = orderIds;
          return this;
        }
            public Payment.Builder updateTime(ZonedDateTime updateTime) {
              this.instance.updateTime = updateTime;
          return this;
        }
            public Payment.Builder externalTransactionId(String externalTransactionId) {
              this.instance.externalTransactionId = externalTransactionId;
          return this;
        }
            public Payment.Builder merchantAccountId(String merchantAccountId) {
              this.instance.merchantAccountId = merchantAccountId;
          return this;
        }
            public Payment.Builder merchantAccountType(MerchantAccountTypeEnum merchantAccountType) {
              this.instance.merchantAccountType = merchantAccountType;
          return this;
        }
            public Payment.Builder paymentMethod(PaymentMethod paymentMethod) {
              this.instance.paymentMethod = paymentMethod;
          return this;
        }
        
    
        /**
        * returns a built Payment instance.
        *
        * The builder is not reusable.
        */
        public Payment build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static Payment.Builder builder() {
        return new Payment.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public Payment.Builder toBuilder() {
        return new Payment.Builder()
          .id(getId())
          .type(getType())
          .amount(getAmount())
          .note(getNote())
          .status(getStatus())
          .commissioned(getCommissioned())
          .synced(getSynced())
          .paymentTime(getPaymentTime())
          .refundPaymentId(getRefundPaymentId())
          .contactId(getContactId())
          .orderIds(getOrderIds())
          .updateTime(getUpdateTime())
          .externalTransactionId(getExternalTransactionId())
          .merchantAccountId(getMerchantAccountId())
          .merchantAccountType(getMerchantAccountType())
          .paymentMethod(getPaymentMethod());
      }
}

