/*
 * Keap REST API
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.812056
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.PipelineCustomFieldRefType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * Class representing the property type for a reference custom field.
 */
@Schema(description = "Class representing the property type for a reference custom field.")
@JsonPropertyOrder({
  PipelineCustomFieldRefPropertyType.JSON_PROPERTY_REFERENCE_TYPE,
  PipelineCustomFieldRefPropertyType.JSON_PROPERTY_FIELDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PipelineCustomFieldRefPropertyType implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_REFERENCE_TYPE = "reference_type";
  @jakarta.annotation.Nonnull  private PipelineCustomFieldRefType referenceType;

  public static final String JSON_PROPERTY_FIELDS = "fields";
  @jakarta.annotation.Nullable  private List<String> fields;

  public PipelineCustomFieldRefPropertyType() { 
  }

  public PipelineCustomFieldRefPropertyType referenceType(@jakarta.annotation.Nonnull PipelineCustomFieldRefType referenceType) {
    this.referenceType = referenceType;
    return this;
  }

  /**
   * The reference type for the custom field. This field is required.
   * @return referenceType
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The reference type for the custom field. This field is required.")
  @JsonProperty(JSON_PROPERTY_REFERENCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PipelineCustomFieldRefType getReferenceType() {
    return referenceType;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferenceType(@jakarta.annotation.Nonnull PipelineCustomFieldRefType referenceType) {
    this.referenceType = referenceType;
  }


  public PipelineCustomFieldRefPropertyType fields(@jakarta.annotation.Nullable List<String> fields) {
    this.fields = fields;
    return this;
  }

  public PipelineCustomFieldRefPropertyType addFieldsItem(String fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

  /**
   * The list of fields for the reference custom field.
   * @return fields
   */
  @jakarta.annotation.Nullable  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The list of fields for the reference custom field.")
  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getFields() {
    return fields;
  }


  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFields(@jakarta.annotation.Nullable List<String> fields) {
    this.fields = fields;
  }

  /**
   * Return true if this PipelineCustomFieldRefPropertyType object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PipelineCustomFieldRefPropertyType pipelineCustomFieldRefPropertyType = (PipelineCustomFieldRefPropertyType) o;
    return Objects.equals(this.referenceType, pipelineCustomFieldRefPropertyType.referenceType) &&
        Objects.equals(this.fields, pipelineCustomFieldRefPropertyType.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceType, fields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PipelineCustomFieldRefPropertyType {\n");
    sb.append("    referenceType: ").append(toIndentedString(referenceType)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private PipelineCustomFieldRefPropertyType instance;
    
        public Builder() {
          this(new PipelineCustomFieldRefPropertyType());
        }
    
        protected Builder(PipelineCustomFieldRefPropertyType instance) {
          this.instance = instance;
        }
    
        public PipelineCustomFieldRefPropertyType.Builder referenceType(PipelineCustomFieldRefType referenceType) {
              this.instance.referenceType = referenceType;
          return this;
        }
            public PipelineCustomFieldRefPropertyType.Builder fields(List<String> fields) {
              this.instance.fields = fields;
          return this;
        }
        
    
        /**
        * returns a built PipelineCustomFieldRefPropertyType instance.
        *
        * The builder is not reusable.
        */
        public PipelineCustomFieldRefPropertyType build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static PipelineCustomFieldRefPropertyType.Builder builder() {
        return new PipelineCustomFieldRefPropertyType.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public PipelineCustomFieldRefPropertyType.Builder toBuilder() {
        return new PipelineCustomFieldRefPropertyType.Builder()
          .referenceType(getReferenceType())
          .fields(getFields());
      }
}

