/*
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.CommissionItemRequest;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * UpdateProductCommissionProgramRequest
 */
@JsonPropertyOrder({
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_PERCENTAGE,
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_UNUSED,
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_DOLLAR_AMOUNT,
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_LEVEL1,
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_LEVEL2,
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_PAYOUT_TYPE,
  UpdateProductCommissionProgramRequest.JSON_PROPERTY_PRODUCT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UpdateProductCommissionProgramRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PERCENTAGE = "percentage";
  @jakarta.annotation.Nullable  private String percentage;

  public static final String JSON_PROPERTY_UNUSED = "unused";
  @jakarta.annotation.Nullable  private CommissionItemRequest unused;

  public static final String JSON_PROPERTY_DOLLAR_AMOUNT = "dollar_amount";
  @jakarta.annotation.Nullable  private String dollarAmount;

  public static final String JSON_PROPERTY_LEVEL1 = "level_1";
  @jakarta.annotation.Nullable  private CommissionItemRequest level1;

  public static final String JSON_PROPERTY_LEVEL2 = "level_2";
  @jakarta.annotation.Nullable  private CommissionItemRequest level2;

  /**
   * The payout type for this commission.
   */
  public enum PayoutTypeEnum {
    UPFRONT(String.valueOf("UPFRONT")),
    
    PAYMENT_RECEIVED(String.valueOf("PAYMENT_RECEIVED")),
    
    UNKNOWN_COULD_NOT_DESERIALIZE(String.valueOf("unknown_default_open_api"));

    private String value;

    PayoutTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayoutTypeEnum fromValue(String value) {
      for (PayoutTypeEnum b : PayoutTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_COULD_NOT_DESERIALIZE;
    }
  }
  public static final String JSON_PROPERTY_PAYOUT_TYPE = "payout_type";
  @jakarta.annotation.Nullable  private PayoutTypeEnum payoutType = PayoutTypeEnum.UPFRONT;

  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @jakarta.annotation.Nonnull  private String productId;

  public UpdateProductCommissionProgramRequest() { 
  }

  public UpdateProductCommissionProgramRequest percentage(@jakarta.annotation.Nullable String percentage) {
    this.percentage = percentage;
    return this;
  }

  /**
   * Level 1 percentage to be paid for commission (0-100). This will be set for the Sale. This is deprecated for &#x60;level_1&#x60;
   * @return percentage
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable  @Schema(example = "10.5", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Level 1 percentage to be paid for commission (0-100). This will be set for the Sale. This is deprecated for `level_1`")
  @JsonProperty(JSON_PROPERTY_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPercentage() {
    return percentage;
  }


  @JsonProperty(JSON_PROPERTY_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentage(@jakarta.annotation.Nullable String percentage) {
    this.percentage = percentage;
  }


  public UpdateProductCommissionProgramRequest unused(@jakarta.annotation.Nullable CommissionItemRequest unused) {
    this.unused = unused;
    return this;
  }

  /**
   * Payout rules for any unused commissions.
   * @return unused
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Payout rules for any unused commissions.")
  @JsonProperty(JSON_PROPERTY_UNUSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CommissionItemRequest getUnused() {
    return unused;
  }


  @JsonProperty(JSON_PROPERTY_UNUSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnused(@jakarta.annotation.Nullable CommissionItemRequest unused) {
    this.unused = unused;
  }


  public UpdateProductCommissionProgramRequest dollarAmount(@jakarta.annotation.Nullable String dollarAmount) {
    this.dollarAmount = dollarAmount;
    return this;
  }

  /**
   * Level 1 fixed dollar amount to be paid for commission. This will be set for the Sale. This is deprecated for &#x60;level_1&#x60;
   * @return dollarAmount
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable  @Schema(example = "25", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Level 1 fixed dollar amount to be paid for commission. This will be set for the Sale. This is deprecated for `level_1`")
  @JsonProperty(JSON_PROPERTY_DOLLAR_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDollarAmount() {
    return dollarAmount;
  }


  @JsonProperty(JSON_PROPERTY_DOLLAR_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDollarAmount(@jakarta.annotation.Nullable String dollarAmount) {
    this.dollarAmount = dollarAmount;
  }


  public UpdateProductCommissionProgramRequest level1(@jakarta.annotation.Nullable CommissionItemRequest level1) {
    this.level1 = level1;
    return this;
  }

  /**
   * Payout rules for Level 1 recipients of the commission.
   * @return level1
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Payout rules for Level 1 recipients of the commission.")
  @JsonProperty(JSON_PROPERTY_LEVEL1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CommissionItemRequest getLevel1() {
    return level1;
  }


  @JsonProperty(JSON_PROPERTY_LEVEL1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel1(@jakarta.annotation.Nullable CommissionItemRequest level1) {
    this.level1 = level1;
  }


  public UpdateProductCommissionProgramRequest level2(@jakarta.annotation.Nullable CommissionItemRequest level2) {
    this.level2 = level2;
    return this;
  }

  /**
   * Payout rules for Level 2 recipients of the commission.
   * @return level2
   */
  @jakarta.annotation.Nullable  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Payout rules for Level 2 recipients of the commission.")
  @JsonProperty(JSON_PROPERTY_LEVEL2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CommissionItemRequest getLevel2() {
    return level2;
  }


  @JsonProperty(JSON_PROPERTY_LEVEL2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel2(@jakarta.annotation.Nullable CommissionItemRequest level2) {
    this.level2 = level2;
  }


  public UpdateProductCommissionProgramRequest payoutType(@jakarta.annotation.Nullable PayoutTypeEnum payoutType) {
    this.payoutType = payoutType;
    return this;
  }

  /**
   * The payout type for this commission.
   * @return payoutType
   */
  @jakarta.annotation.Nullable  @Schema(example = "UPFRONT", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The payout type for this commission.")
  @JsonProperty(JSON_PROPERTY_PAYOUT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PayoutTypeEnum getPayoutType() {
    return payoutType;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutType(@jakarta.annotation.Nullable PayoutTypeEnum payoutType) {
    this.payoutType = payoutType;
  }


  public UpdateProductCommissionProgramRequest productId(@jakarta.annotation.Nonnull String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Product ID to assign commission
   * @return productId
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(example = "123", requiredMode = Schema.RequiredMode.REQUIRED, description = "Product ID to assign commission")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(@jakarta.annotation.Nonnull String productId) {
    this.productId = productId;
  }

  /**
   * Return true if this UpdateProductCommissionProgramRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateProductCommissionProgramRequest updateProductCommissionProgramRequest = (UpdateProductCommissionProgramRequest) o;
    return Objects.equals(this.percentage, updateProductCommissionProgramRequest.percentage) &&
        Objects.equals(this.unused, updateProductCommissionProgramRequest.unused) &&
        Objects.equals(this.dollarAmount, updateProductCommissionProgramRequest.dollarAmount) &&
        Objects.equals(this.level1, updateProductCommissionProgramRequest.level1) &&
        Objects.equals(this.level2, updateProductCommissionProgramRequest.level2) &&
        Objects.equals(this.payoutType, updateProductCommissionProgramRequest.payoutType) &&
        Objects.equals(this.productId, updateProductCommissionProgramRequest.productId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(percentage, unused, dollarAmount, level1, level2, payoutType, productId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateProductCommissionProgramRequest {\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    unused: ").append(toIndentedString(unused)).append("\n");
    sb.append("    dollarAmount: ").append(toIndentedString(dollarAmount)).append("\n");
    sb.append("    level1: ").append(toIndentedString(level1)).append("\n");
    sb.append("    level2: ").append(toIndentedString(level2)).append("\n");
    sb.append("    payoutType: ").append(toIndentedString(payoutType)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private UpdateProductCommissionProgramRequest instance;
    
        public Builder() {
          this(new UpdateProductCommissionProgramRequest());
        }
    
        protected Builder(UpdateProductCommissionProgramRequest instance) {
          this.instance = instance;
        }
    
        public UpdateProductCommissionProgramRequest.Builder percentage(String percentage) {
              this.instance.percentage = percentage;
          return this;
        }
            public UpdateProductCommissionProgramRequest.Builder unused(CommissionItemRequest unused) {
              this.instance.unused = unused;
          return this;
        }
            public UpdateProductCommissionProgramRequest.Builder dollarAmount(String dollarAmount) {
              this.instance.dollarAmount = dollarAmount;
          return this;
        }
            public UpdateProductCommissionProgramRequest.Builder level1(CommissionItemRequest level1) {
              this.instance.level1 = level1;
          return this;
        }
            public UpdateProductCommissionProgramRequest.Builder level2(CommissionItemRequest level2) {
              this.instance.level2 = level2;
          return this;
        }
            public UpdateProductCommissionProgramRequest.Builder payoutType(PayoutTypeEnum payoutType) {
              this.instance.payoutType = payoutType;
          return this;
        }
            public UpdateProductCommissionProgramRequest.Builder productId(String productId) {
              this.instance.productId = productId;
          return this;
        }
        
    
        /**
        * returns a built UpdateProductCommissionProgramRequest instance.
        *
        * The builder is not reusable.
        */
        public UpdateProductCommissionProgramRequest build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static UpdateProductCommissionProgramRequest.Builder builder() {
        return new UpdateProductCommissionProgramRequest.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public UpdateProductCommissionProgramRequest.Builder toBuilder() {
        return new UpdateProductCommissionProgramRequest.Builder()
          .percentage(getPercentage())
          .unused(getUnused())
          .dollarAmount(getDollarAmount())
          .level1(getLevel1())
          .level2(getLevel2())
          .payoutType(getPayoutType())
          .productId(getProductId());
      }
}

