/*
 * Keap REST API
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.809589
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keap.core.sdk.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.keap.core.sdk.model.PipelineCustomFieldDisplayOptions;
import com.keap.core.sdk.model.PipelineCustomFieldOptions;
import com.keap.core.sdk.model.PipelineCustomFieldPropertyValidator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


/**
 * Represents a request to update a custom field.
 */
@Schema(description = "Represents a request to update a custom field.")
@JsonPropertyOrder({
  UpdateCustomFieldRequest.JSON_PROPERTY_LABEL,
  UpdateCustomFieldRequest.JSON_PROPERTY_DESCRIPTION,
  UpdateCustomFieldRequest.JSON_PROPERTY_HINT,
  UpdateCustomFieldRequest.JSON_PROPERTY_HELPER_TEXT,
  UpdateCustomFieldRequest.JSON_PROPERTY_DEFAULT_VALUE,
  UpdateCustomFieldRequest.JSON_PROPERTY_DISPLAY_OPTIONS,
  UpdateCustomFieldRequest.JSON_PROPERTY_OPTIONS,
  UpdateCustomFieldRequest.JSON_PROPERTY_VALIDATORS,
  UpdateCustomFieldRequest.JSON_PROPERTY_DELETED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UpdateCustomFieldRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nonnull  private String label;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull  private String description;

  public static final String JSON_PROPERTY_HINT = "hint";
  @jakarta.annotation.Nonnull  private String hint;

  public static final String JSON_PROPERTY_HELPER_TEXT = "helper_text";
  @jakarta.annotation.Nonnull  private String helperText;

  public static final String JSON_PROPERTY_DEFAULT_VALUE = "default_value";
  @jakarta.annotation.Nonnull  private Object defaultValue;

  public static final String JSON_PROPERTY_DISPLAY_OPTIONS = "display_options";
  @jakarta.annotation.Nonnull  private PipelineCustomFieldDisplayOptions displayOptions;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nonnull  private PipelineCustomFieldOptions options;

  public static final String JSON_PROPERTY_VALIDATORS = "validators";
  @jakarta.annotation.Nonnull  private List<@Valid PipelineCustomFieldPropertyValidator> validators = new ArrayList<>();

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @jakarta.annotation.Nonnull  private Boolean deleted;

  public UpdateCustomFieldRequest() { 
  }

  public UpdateCustomFieldRequest label(@jakarta.annotation.Nonnull String label) {
    this.label = label;
    return this;
  }

  /**
   * The label of the custom field.
   * @return label
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The label of the custom field.")
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(@jakarta.annotation.Nonnull String label) {
    this.label = label;
  }


  public UpdateCustomFieldRequest description(@jakarta.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the custom field.
   * @return description
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The description of the custom field.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }


  public UpdateCustomFieldRequest hint(@jakarta.annotation.Nonnull String hint) {
    this.hint = hint;
    return this;
  }

  /**
   * The hint for the custom field.
   * @return hint
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The hint for the custom field.")
  @JsonProperty(JSON_PROPERTY_HINT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHint() {
    return hint;
  }


  @JsonProperty(JSON_PROPERTY_HINT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHint(@jakarta.annotation.Nonnull String hint) {
    this.hint = hint;
  }


  public UpdateCustomFieldRequest helperText(@jakarta.annotation.Nonnull String helperText) {
    this.helperText = helperText;
    return this;
  }

  /**
   * The helper text for the custom field.
   * @return helperText
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The helper text for the custom field.")
  @JsonProperty(JSON_PROPERTY_HELPER_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHelperText() {
    return helperText;
  }


  @JsonProperty(JSON_PROPERTY_HELPER_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHelperText(@jakarta.annotation.Nonnull String helperText) {
    this.helperText = helperText;
  }


  public UpdateCustomFieldRequest defaultValue(@jakarta.annotation.Nonnull Object defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * The default value of the custom field.
   * @return defaultValue
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The default value of the custom field.")
  @JsonProperty(JSON_PROPERTY_DEFAULT_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Object getDefaultValue() {
    return defaultValue;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDefaultValue(@jakarta.annotation.Nonnull Object defaultValue) {
    this.defaultValue = defaultValue;
  }


  public UpdateCustomFieldRequest displayOptions(@jakarta.annotation.Nonnull PipelineCustomFieldDisplayOptions displayOptions) {
    this.displayOptions = displayOptions;
    return this;
  }

  /**
   * The display options for the custom field.
   * @return displayOptions
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The display options for the custom field.")
  @JsonProperty(JSON_PROPERTY_DISPLAY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PipelineCustomFieldDisplayOptions getDisplayOptions() {
    return displayOptions;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayOptions(@jakarta.annotation.Nonnull PipelineCustomFieldDisplayOptions displayOptions) {
    this.displayOptions = displayOptions;
  }


  public UpdateCustomFieldRequest options(@jakarta.annotation.Nonnull PipelineCustomFieldOptions options) {
    this.options = options;
    return this;
  }

  /**
   * The options for the custom field.
   * @return options
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The options for the custom field.")
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PipelineCustomFieldOptions getOptions() {
    return options;
  }


  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptions(@jakarta.annotation.Nonnull PipelineCustomFieldOptions options) {
    this.options = options;
  }


  public UpdateCustomFieldRequest validators(@jakarta.annotation.Nonnull List<@Valid PipelineCustomFieldPropertyValidator> validators) {
    this.validators = validators;
    return this;
  }

  public UpdateCustomFieldRequest addValidatorsItem(PipelineCustomFieldPropertyValidator validatorsItem) {
    if (this.validators == null) {
      this.validators = new ArrayList<>();
    }
    this.validators.add(validatorsItem);
    return this;
  }

  /**
   * The validators for the custom field.
   * @return validators
   */
  @jakarta.annotation.Nonnull  @NotNull
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "The validators for the custom field.")
  @JsonProperty(JSON_PROPERTY_VALIDATORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid PipelineCustomFieldPropertyValidator> getValidators() {
    return validators;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidators(@jakarta.annotation.Nonnull List<@Valid PipelineCustomFieldPropertyValidator> validators) {
    this.validators = validators;
  }


  public UpdateCustomFieldRequest deleted(@jakarta.annotation.Nonnull Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Indicates whether the custom field is deleted.
   * @return deleted
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nonnull  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Indicates whether the custom field is deleted.")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeleted(@jakarta.annotation.Nonnull Boolean deleted) {
    this.deleted = deleted;
  }

  /**
   * Return true if this UpdateCustomFieldRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCustomFieldRequest updateCustomFieldRequest = (UpdateCustomFieldRequest) o;
    return Objects.equals(this.label, updateCustomFieldRequest.label) &&
        Objects.equals(this.description, updateCustomFieldRequest.description) &&
        Objects.equals(this.hint, updateCustomFieldRequest.hint) &&
        Objects.equals(this.helperText, updateCustomFieldRequest.helperText) &&
        Objects.equals(this.defaultValue, updateCustomFieldRequest.defaultValue) &&
        Objects.equals(this.displayOptions, updateCustomFieldRequest.displayOptions) &&
        Objects.equals(this.options, updateCustomFieldRequest.options) &&
        Objects.equals(this.validators, updateCustomFieldRequest.validators) &&
        Objects.equals(this.deleted, updateCustomFieldRequest.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, description, hint, helperText, defaultValue, displayOptions, options, validators, deleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCustomFieldRequest {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hint: ").append(toIndentedString(hint)).append("\n");
    sb.append("    helperText: ").append(toIndentedString(helperText)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    displayOptions: ").append(toIndentedString(displayOptions)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    validators: ").append(toIndentedString(validators)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public static class Builder {
    
        private UpdateCustomFieldRequest instance;
    
        public Builder() {
          this(new UpdateCustomFieldRequest());
        }
    
        protected Builder(UpdateCustomFieldRequest instance) {
          this.instance = instance;
        }
    
        public UpdateCustomFieldRequest.Builder label(String label) {
              this.instance.label = label;
          return this;
        }
            public UpdateCustomFieldRequest.Builder description(String description) {
              this.instance.description = description;
          return this;
        }
            public UpdateCustomFieldRequest.Builder hint(String hint) {
              this.instance.hint = hint;
          return this;
        }
            public UpdateCustomFieldRequest.Builder helperText(String helperText) {
              this.instance.helperText = helperText;
          return this;
        }
            public UpdateCustomFieldRequest.Builder defaultValue(Object defaultValue) {
              this.instance.defaultValue = defaultValue;
          return this;
        }
            public UpdateCustomFieldRequest.Builder displayOptions(PipelineCustomFieldDisplayOptions displayOptions) {
              this.instance.displayOptions = displayOptions;
          return this;
        }
            public UpdateCustomFieldRequest.Builder options(PipelineCustomFieldOptions options) {
              this.instance.options = options;
          return this;
        }
            public UpdateCustomFieldRequest.Builder validators(List<PipelineCustomFieldPropertyValidator> validators) {
              this.instance.validators = validators;
          return this;
        }
            public UpdateCustomFieldRequest.Builder deleted(Boolean deleted) {
              this.instance.deleted = deleted;
          return this;
        }
        
    
        /**
        * returns a built UpdateCustomFieldRequest instance.
        *
        * The builder is not reusable.
        */
        public UpdateCustomFieldRequest build() {
          try {
            return this.instance;
          } finally {
            // ensure that this.instance is not reused
            this.instance = null;
          }
        }
    
        @Override
        public String toString() {
          return getClass() + "=(" + instance + ")";
        }
      }
    
      /**
      * Create a builder with no initialized field.
      */
      public static UpdateCustomFieldRequest.Builder builder() {
        return new UpdateCustomFieldRequest.Builder();
      }
    
      /**
      * Create a builder with a shallow copy of this instance.
      */
      public UpdateCustomFieldRequest.Builder toBuilder() {
        return new UpdateCustomFieldRequest.Builder()
          .label(getLabel())
          .description(getDescription())
          .hint(getHint())
          .helperText(getHelperText())
          .defaultValue(getDefaultValue())
          .displayOptions(getDisplayOptions())
          .options(getOptions())
          .validators(getValidators())
          .deleted(getDeleted());
      }
}

