/**
 * Keap REST API
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.863963
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestAffiliatePayment from './RestAffiliatePayment';

/**
 * The ListAffiliatePaymentsResponse model module.
 * @module keap.core.v2/model/ListAffiliatePaymentsResponse
 */
class ListAffiliatePaymentsResponse {
    /**
     * Constructs a new <code>ListAffiliatePaymentsResponse</code>.
     * @alias module:keap.core.v2/model/ListAffiliatePaymentsResponse
     */
    constructor() { 
        
        ListAffiliatePaymentsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListAffiliatePaymentsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:keap.core.v2/model/ListAffiliatePaymentsResponse} obj Optional instance to populate.
     * @return {module:keap.core.v2/model/ListAffiliatePaymentsResponse} The populated <code>ListAffiliatePaymentsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListAffiliatePaymentsResponse();

            if (data.hasOwnProperty('affiliate_payments')) {
                obj['affiliate_payments'] = ApiClient.convertToType(data['affiliate_payments'], [RestAffiliatePayment]);
            }
            if (data.hasOwnProperty('next_page_token')) {
                obj['next_page_token'] = ApiClient.convertToType(data['next_page_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListAffiliatePaymentsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListAffiliatePaymentsResponse</code>.
     */
    static validateJSON(data) {
        if (data['affiliate_payments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['affiliate_payments'])) {
                throw new Error("Expected the field `affiliate_payments` to be an array in the JSON data but got " + data['affiliate_payments']);
            }
            // validate the optional field `affiliate_payments` (array)
            for (const item of data['affiliate_payments']) {
                RestAffiliatePayment.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page_token'] && !(typeof data['next_page_token'] === 'string' || data['next_page_token'] instanceof String)) {
            throw new Error("Expected the field `next_page_token` to be a primitive type in the JSON string but got " + data['next_page_token']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:keap.core.v2/model/RestAffiliatePayment>} affiliate_payments
 */
ListAffiliatePaymentsResponse.prototype['affiliate_payments'] = undefined;

/**
 * @member {String} next_page_token
 */
ListAffiliatePaymentsResponse.prototype['next_page_token'] = undefined;






export default ListAffiliatePaymentsResponse;
