/**
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestEmailAddressStatus from './RestEmailAddressStatus';

/**
 * The ListEmailAddressStatusResponse model module.
 * @module keap.core.v2/model/ListEmailAddressStatusResponse
 */
class ListEmailAddressStatusResponse {
    /**
     * Constructs a new <code>ListEmailAddressStatusResponse</code>.
     * @alias module:keap.core.v2/model/ListEmailAddressStatusResponse
     */
    constructor() { 
        
        ListEmailAddressStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListEmailAddressStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:keap.core.v2/model/ListEmailAddressStatusResponse} obj Optional instance to populate.
     * @return {module:keap.core.v2/model/ListEmailAddressStatusResponse} The populated <code>ListEmailAddressStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListEmailAddressStatusResponse();

            if (data.hasOwnProperty('email_addresses')) {
                obj['email_addresses'] = ApiClient.convertToType(data['email_addresses'], [RestEmailAddressStatus]);
            }
            if (data.hasOwnProperty('next_page_token')) {
                obj['next_page_token'] = ApiClient.convertToType(data['next_page_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListEmailAddressStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListEmailAddressStatusResponse</code>.
     */
    static validateJSON(data) {
        if (data['email_addresses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['email_addresses'])) {
                throw new Error("Expected the field `email_addresses` to be an array in the JSON data but got " + data['email_addresses']);
            }
            // validate the optional field `email_addresses` (array)
            for (const item of data['email_addresses']) {
                RestEmailAddressStatus.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page_token'] && !(typeof data['next_page_token'] === 'string' || data['next_page_token'] instanceof String)) {
            throw new Error("Expected the field `next_page_token` to be a primitive type in the JSON string but got " + data['next_page_token']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:keap.core.v2/model/RestEmailAddressStatus>} email_addresses
 */
ListEmailAddressStatusResponse.prototype['email_addresses'] = undefined;

/**
 * @member {String} next_page_token
 */
ListEmailAddressStatusResponse.prototype['next_page_token'] = undefined;






export default ListEmailAddressStatusResponse;
