/**
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AffiliateProgramResource from './AffiliateProgramResource';

/**
 * The ListProgramResourcesResponse model module.
 * @module keap.core.v2/model/ListProgramResourcesResponse
 */
class ListProgramResourcesResponse {
    /**
     * Constructs a new <code>ListProgramResourcesResponse</code>.
     * @alias module:keap.core.v2/model/ListProgramResourcesResponse
     */
    constructor() { 
        
        ListProgramResourcesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListProgramResourcesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:keap.core.v2/model/ListProgramResourcesResponse} obj Optional instance to populate.
     * @return {module:keap.core.v2/model/ListProgramResourcesResponse} The populated <code>ListProgramResourcesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListProgramResourcesResponse();

            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], [AffiliateProgramResource]);
            }
            if (data.hasOwnProperty('next_page_token')) {
                obj['next_page_token'] = ApiClient.convertToType(data['next_page_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListProgramResourcesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListProgramResourcesResponse</code>.
     */
    static validateJSON(data) {
        if (data['resources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['resources'])) {
                throw new Error("Expected the field `resources` to be an array in the JSON data but got " + data['resources']);
            }
            // validate the optional field `resources` (array)
            for (const item of data['resources']) {
                AffiliateProgramResource.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page_token'] && !(typeof data['next_page_token'] === 'string' || data['next_page_token'] instanceof String)) {
            throw new Error("Expected the field `next_page_token` to be a primitive type in the JSON string but got " + data['next_page_token']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:keap.core.v2/model/AffiliateProgramResource>} resources
 */
ListProgramResourcesResponse.prototype['resources'] = undefined;

/**
 * @member {String} next_page_token
 */
ListProgramResourcesResponse.prototype['next_page_token'] = undefined;






export default ListProgramResourcesResponse;
