/**
 * Keap REST API
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.812056
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PipelineCustomFieldRefType from './PipelineCustomFieldRefType';

/**
 * The PipelineCustomFieldRefPropertyType model module.
 * @module keap.core.v2/model/PipelineCustomFieldRefPropertyType
 */
class PipelineCustomFieldRefPropertyType {
    /**
     * Constructs a new <code>PipelineCustomFieldRefPropertyType</code>.
     * Class representing the property type for a reference custom field.
     * @alias module:keap.core.v2/model/PipelineCustomFieldRefPropertyType
     * @param referenceType {module:keap.core.v2/model/PipelineCustomFieldRefType} The reference type for the custom field. This field is required.
     */
    constructor(referenceType) { 
        
        PipelineCustomFieldRefPropertyType.initialize(this, referenceType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, referenceType) { 
        obj['reference_type'] = referenceType;
    }

    /**
     * Constructs a <code>PipelineCustomFieldRefPropertyType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:keap.core.v2/model/PipelineCustomFieldRefPropertyType} obj Optional instance to populate.
     * @return {module:keap.core.v2/model/PipelineCustomFieldRefPropertyType} The populated <code>PipelineCustomFieldRefPropertyType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PipelineCustomFieldRefPropertyType();

            if (data.hasOwnProperty('reference_type')) {
                obj['reference_type'] = ApiClient.convertToType(data['reference_type'], PipelineCustomFieldRefType);
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PipelineCustomFieldRefPropertyType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PipelineCustomFieldRefPropertyType</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PipelineCustomFieldRefPropertyType.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `reference_type`
        if (data['reference_type']) { // data not null
          PipelineCustomFieldRefType.validateJSON(data['reference_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['fields'])) {
            throw new Error("Expected the field `fields` to be an array in the JSON data but got " + data['fields']);
        }

        return true;
    }


}

PipelineCustomFieldRefPropertyType.RequiredProperties = ["reference_type"];

/**
 * The reference type for the custom field. This field is required.
 * @member {module:keap.core.v2/model/PipelineCustomFieldRefType} reference_type
 */
PipelineCustomFieldRefPropertyType.prototype['reference_type'] = undefined;

/**
 * The list of fields for the reference custom field.
 * @member {Array.<String>} fields
 */
PipelineCustomFieldRefPropertyType.prototype['fields'] = undefined;






export default PipelineCustomFieldRefPropertyType;
