/**
 * Keap API
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestUpdatePaymentRequest model module.
 * @module keap.core.v2/model/RestUpdatePaymentRequest
 */
class RestUpdatePaymentRequest {
    /**
     * Constructs a new <code>RestUpdatePaymentRequest</code>.
     * @alias module:keap.core.v2/model/RestUpdatePaymentRequest
     */
    constructor() { 
        
        RestUpdatePaymentRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestUpdatePaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:keap.core.v2/model/RestUpdatePaymentRequest} obj Optional instance to populate.
     * @return {module:keap.core.v2/model/RestUpdatePaymentRequest} The populated <code>RestUpdatePaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestUpdatePaymentRequest();

            if (data.hasOwnProperty('external_source')) {
                obj['external_source'] = ApiClient.convertToType(data['external_source'], 'String');
            }
            if (data.hasOwnProperty('external_source_value')) {
                obj['external_source_value'] = ApiClient.convertToType(data['external_source_value'], 'String');
            }
            if (data.hasOwnProperty('external_status_value')) {
                obj['external_status_value'] = ApiClient.convertToType(data['external_status_value'], 'String');
            }
            if (data.hasOwnProperty('external_create_time')) {
                obj['external_create_time'] = ApiClient.convertToType(data['external_create_time'], 'Date');
            }
            if (data.hasOwnProperty('external_update_time')) {
                obj['external_update_time'] = ApiClient.convertToType(data['external_update_time'], 'Date');
            }
            if (data.hasOwnProperty('external_create_user')) {
                obj['external_create_user'] = ApiClient.convertToType(data['external_create_user'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('payment_time')) {
                obj['payment_time'] = ApiClient.convertToType(data['payment_time'], 'Date');
            }
            if (data.hasOwnProperty('payment_amount')) {
                obj['payment_amount'] = ApiClient.convertToType(data['payment_amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RestUpdatePaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RestUpdatePaymentRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['external_source'] && !(typeof data['external_source'] === 'string' || data['external_source'] instanceof String)) {
            throw new Error("Expected the field `external_source` to be a primitive type in the JSON string but got " + data['external_source']);
        }
        // ensure the json data is a string
        if (data['external_source_value'] && !(typeof data['external_source_value'] === 'string' || data['external_source_value'] instanceof String)) {
            throw new Error("Expected the field `external_source_value` to be a primitive type in the JSON string but got " + data['external_source_value']);
        }
        // ensure the json data is a string
        if (data['external_status_value'] && !(typeof data['external_status_value'] === 'string' || data['external_status_value'] instanceof String)) {
            throw new Error("Expected the field `external_status_value` to be a primitive type in the JSON string but got " + data['external_status_value']);
        }
        // ensure the json data is a string
        if (data['external_create_user'] && !(typeof data['external_create_user'] === 'string' || data['external_create_user'] instanceof String)) {
            throw new Error("Expected the field `external_create_user` to be a primitive type in the JSON string but got " + data['external_create_user']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}



/**
 * The external source type of this payment.
 * @member {String} external_source
 */
RestUpdatePaymentRequest.prototype['external_source'] = undefined;

/**
 * The external source value of this payment.
 * @member {String} external_source_value
 */
RestUpdatePaymentRequest.prototype['external_source_value'] = undefined;

/**
 * The external status value of this payment.
 * @member {String} external_status_value
 */
RestUpdatePaymentRequest.prototype['external_status_value'] = undefined;

/**
 * The external creation timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
 * @member {Date} external_create_time
 */
RestUpdatePaymentRequest.prototype['external_create_time'] = undefined;

/**
 * The external update timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
 * @member {Date} external_update_time
 */
RestUpdatePaymentRequest.prototype['external_update_time'] = undefined;

/**
 * The user who created this payment externally.
 * @member {String} external_create_user
 */
RestUpdatePaymentRequest.prototype['external_create_user'] = undefined;

/**
 * Notes or description for the payment.
 * @member {String} notes
 */
RestUpdatePaymentRequest.prototype['notes'] = undefined;

/**
 * The date and time of payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z). Can only be modified for manually recorded payments.
 * @member {Date} payment_time
 */
RestUpdatePaymentRequest.prototype['payment_time'] = undefined;

/**
 * The payment amount. Can only be modified for manually recorded payments.
 * @member {Number} payment_amount
 */
RestUpdatePaymentRequest.prototype['payment_amount'] = undefined;






export default RestUpdatePaymentRequest;
