/**
 * Keap REST API
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.834462-hf-202507221415
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdatedPaymentPlan model module.
 * @module keap.core.v2/model/UpdatedPaymentPlan
 */
class UpdatedPaymentPlan {
    /**
     * Constructs a new <code>UpdatedPaymentPlan</code>.
     * @alias module:keap.core.v2/model/UpdatedPaymentPlan
     */
    constructor() { 
        
        UpdatedPaymentPlan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdatedPaymentPlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:keap.core.v2/model/UpdatedPaymentPlan} obj Optional instance to populate.
     * @return {module:keap.core.v2/model/UpdatedPaymentPlan} The populated <code>UpdatedPaymentPlan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatedPaymentPlan();

            if (data.hasOwnProperty('auto_charge')) {
                obj['auto_charge'] = ApiClient.convertToType(data['auto_charge'], 'Boolean');
            }
            if (data.hasOwnProperty('days_between_payments')) {
                obj['days_between_payments'] = ApiClient.convertToType(data['days_between_payments'], 'Number');
            }
            if (data.hasOwnProperty('days_between_retries')) {
                obj['days_between_retries'] = ApiClient.convertToType(data['days_between_retries'], 'Number');
            }
            if (data.hasOwnProperty('initial_payment_amount')) {
                obj['initial_payment_amount'] = ApiClient.convertToType(data['initial_payment_amount'], 'Number');
            }
            if (data.hasOwnProperty('initial_payment_date')) {
                obj['initial_payment_date'] = ApiClient.convertToType(data['initial_payment_date'], 'String');
            }
            if (data.hasOwnProperty('max_charge_attempts')) {
                obj['max_charge_attempts'] = ApiClient.convertToType(data['max_charge_attempts'], 'Number');
            }
            if (data.hasOwnProperty('number_of_payments')) {
                obj['number_of_payments'] = ApiClient.convertToType(data['number_of_payments'], 'Number');
            }
            if (data.hasOwnProperty('payment_method_id')) {
                obj['payment_method_id'] = ApiClient.convertToType(data['payment_method_id'], 'String');
            }
            if (data.hasOwnProperty('plan_start_date')) {
                obj['plan_start_date'] = ApiClient.convertToType(data['plan_start_date'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdatedPaymentPlan</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdatedPaymentPlan</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['initial_payment_date'] && !(typeof data['initial_payment_date'] === 'string' || data['initial_payment_date'] instanceof String)) {
            throw new Error("Expected the field `initial_payment_date` to be a primitive type in the JSON string but got " + data['initial_payment_date']);
        }
        // ensure the json data is a string
        if (data['payment_method_id'] && !(typeof data['payment_method_id'] === 'string' || data['payment_method_id'] instanceof String)) {
            throw new Error("Expected the field `payment_method_id` to be a primitive type in the JSON string but got " + data['payment_method_id']);
        }
        // ensure the json data is a string
        if (data['plan_start_date'] && !(typeof data['plan_start_date'] === 'string' || data['plan_start_date'] instanceof String)) {
            throw new Error("Expected the field `plan_start_date` to be a primitive type in the JSON string but got " + data['plan_start_date']);
        }

        return true;
    }


}



/**
 * @member {Boolean} auto_charge
 */
UpdatedPaymentPlan.prototype['auto_charge'] = undefined;

/**
 * @member {Number} days_between_payments
 */
UpdatedPaymentPlan.prototype['days_between_payments'] = undefined;

/**
 * @member {Number} days_between_retries
 */
UpdatedPaymentPlan.prototype['days_between_retries'] = undefined;

/**
 * @member {Number} initial_payment_amount
 */
UpdatedPaymentPlan.prototype['initial_payment_amount'] = undefined;

/**
 * ISO date of the initial payment in pay plan. e.g 2024-04-28
 * @member {String} initial_payment_date
 */
UpdatedPaymentPlan.prototype['initial_payment_date'] = undefined;

/**
 * @member {Number} max_charge_attempts
 */
UpdatedPaymentPlan.prototype['max_charge_attempts'] = undefined;

/**
 * @member {Number} number_of_payments
 */
UpdatedPaymentPlan.prototype['number_of_payments'] = undefined;

/**
 * @member {String} payment_method_id
 */
UpdatedPaymentPlan.prototype['payment_method_id'] = undefined;

/**
 * ISO date of the start of pay plan. e.g 2024-04-28
 * @member {String} plan_start_date
 */
UpdatedPaymentPlan.prototype['plan_start_date'] = undefined;






export default UpdatedPaymentPlan;
