# coding: utf-8

"""
    Keap API

    Keap Public API Documentation

    The version of the OpenAPI document: v2
    Contact: api.keap@thryv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from keap_core_v2_client.models.automation_lock_status import AutomationLockStatus
from typing import Optional, Set
from typing_extensions import Self

class Automation(BaseModel):
    """
    Automation
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the automation")
    title: Optional[StrictStr] = Field(default=None, description="The title of the automation")
    categories: Optional[List[StrictStr]] = Field(default=None, description="List of category IDs associated with this automation")
    status: Optional[StrictStr] = Field(default=None, description="The publication status of the automation")
    locked: Optional[StrictBool] = Field(default=None, description="Whether the automation is locked for editing")
    active_contacts: Optional[StrictInt] = Field(default=None, description="Number of contacts currently active in this automation")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message if the automation has issues")
    published_date: Optional[datetime] = Field(default=None, description="The date and time when the automation was published. In ISO-8601 format")
    published_by: Optional[StrictStr] = Field(default=None, description="The user ID who published the automation")
    published_timezone: Optional[StrictStr] = Field(default=None, description="The timezone used when publishing")
    current_edit_lock_status: Optional[AutomationLockStatus] = Field(default=None, description="Current edit lock status information")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "title", "categories", "status", "locked", "active_contacts", "error_message", "published_date", "published_by", "published_timezone", "current_edit_lock_status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PUBLISHED', 'DRAFT']):
            raise ValueError("must be one of enum values ('PUBLISHED', 'DRAFT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Automation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_edit_lock_status
        if self.current_edit_lock_status:
            _dict['current_edit_lock_status'] = self.current_edit_lock_status.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Automation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "categories": obj.get("categories"),
            "status": obj.get("status"),
            "locked": obj.get("locked"),
            "active_contacts": obj.get("active_contacts"),
            "error_message": obj.get("error_message"),
            "published_date": obj.get("published_date"),
            "published_by": obj.get("published_by"),
            "published_timezone": obj.get("published_timezone"),
            "current_edit_lock_status": AutomationLockStatus.from_dict(obj["current_edit_lock_status"]) if obj.get("current_edit_lock_status") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


