# coding: utf-8

"""
    Keap API

    Keap Public API Documentation

    The version of the OpenAPI document: v2
    Contact: api.keap@thryv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from keap_core_v2_client.models.address import Address
from keap_core_v2_client.models.custom_field_value import CustomFieldValue
from keap_core_v2_client.models.email_address import EmailAddress
from keap_core_v2_client.models.fax_number import FaxNumber
from keap_core_v2_client.models.phone_number import PhoneNumber
from typing import Optional, Set
from typing_extensions import Self

class Company(BaseModel):
    """
    Company
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier")
    address: Optional[Address] = Field(default=None, description="The company's address")
    notes: Optional[StrictStr] = Field(default=None, description="Notes about the company")
    website: Optional[StrictStr] = Field(default=None, description="The company's website URL")
    suffix: Optional[StrictStr] = Field(default=None, description="Name suffix")
    title: Optional[StrictStr] = Field(default=None, description="Name prefix or salutation")
    groups: Optional[StrictStr] = Field(default=None, description="Comma-delimited list of tag IDs applied to this company")
    company_name: Optional[StrictStr] = Field(default=None, description="The name of the company")
    custom_fields: Optional[List[CustomFieldValue]] = None
    email_address: Optional[EmailAddress] = None
    fax_number: Optional[FaxNumber] = None
    phone_number: Optional[PhoneNumber] = None
    update_time: Optional[StrictStr] = Field(default=None, description="Last update timestamp (ISO-8601)")
    create_time: Optional[StrictStr] = Field(default=None, description="Creation timestamp (ISO-8601)")
    anniversary_date: Optional[StrictStr] = Field(default=None, description="The anniversary date")
    assistant_name: Optional[StrictStr] = Field(default=None, description="The name of the company contact's assistant")
    assistant_phone: Optional[StrictStr] = Field(default=None, description="The phone number of the company contact's assistant")
    billing_information: Optional[StrictStr] = Field(default=None, description="Billing information for the company")
    birth_date: Optional[StrictStr] = Field(default=None, description="The birth date")
    contact_type: Optional[StrictStr] = Field(default=None, description="Type of contact")
    first_name: Optional[StrictStr] = Field(default=None, description="First name of the company contact")
    job_title: Optional[StrictStr] = Field(default=None, description="Job title of the company contact")
    last_name: Optional[StrictStr] = Field(default=None, description="Last name of the company contact")
    middle_name: Optional[StrictStr] = Field(default=None, description="Middle name of the company contact")
    preferred_name: Optional[StrictStr] = Field(default=None, description="Preferred name or nickname of the company contact")
    owner_id: Optional[StrictStr] = Field(default=None, description="ID of the user who owns this company")
    referral_code: Optional[StrictStr] = Field(default=None, description="Referral code")
    spouse_name: Optional[StrictStr] = Field(default=None, description="Spouse's name")
    account_id: Optional[StrictStr] = Field(default=None, description="The company's account ID")
    created_by: Optional[StrictStr] = Field(default=None, description="ID of the user who created this company")
    last_updated_by: Optional[StrictStr] = Field(default=None, description="ID of the user who last updated this company")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "address", "notes", "website", "suffix", "title", "groups", "company_name", "custom_fields", "email_address", "fax_number", "phone_number", "update_time", "create_time", "anniversary_date", "assistant_name", "assistant_phone", "billing_information", "birth_date", "contact_type", "first_name", "job_title", "last_name", "middle_name", "preferred_name", "owner_id", "referral_code", "spouse_name", "account_id", "created_by", "last_updated_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Company from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of email_address
        if self.email_address:
            _dict['email_address'] = self.email_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fax_number
        if self.fax_number:
            _dict['fax_number'] = self.fax_number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phone_number
        if self.phone_number:
            _dict['phone_number'] = self.phone_number.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Company from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "address": Address.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "notes": obj.get("notes"),
            "website": obj.get("website"),
            "suffix": obj.get("suffix"),
            "title": obj.get("title"),
            "groups": obj.get("groups"),
            "company_name": obj.get("company_name"),
            "custom_fields": [CustomFieldValue.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "email_address": EmailAddress.from_dict(obj["email_address"]) if obj.get("email_address") is not None else None,
            "fax_number": FaxNumber.from_dict(obj["fax_number"]) if obj.get("fax_number") is not None else None,
            "phone_number": PhoneNumber.from_dict(obj["phone_number"]) if obj.get("phone_number") is not None else None,
            "update_time": obj.get("update_time"),
            "create_time": obj.get("create_time"),
            "anniversary_date": obj.get("anniversary_date"),
            "assistant_name": obj.get("assistant_name"),
            "assistant_phone": obj.get("assistant_phone"),
            "billing_information": obj.get("billing_information"),
            "birth_date": obj.get("birth_date"),
            "contact_type": obj.get("contact_type"),
            "first_name": obj.get("first_name"),
            "job_title": obj.get("job_title"),
            "last_name": obj.get("last_name"),
            "middle_name": obj.get("middle_name"),
            "preferred_name": obj.get("preferred_name"),
            "owner_id": obj.get("owner_id"),
            "referral_code": obj.get("referral_code"),
            "spouse_name": obj.get("spouse_name"),
            "account_id": obj.get("account_id"),
            "created_by": obj.get("created_by"),
            "last_updated_by": obj.get("last_updated_by")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


