# coding: utf-8

"""
    Keap API

    Keap Public API Documentation

    The version of the OpenAPI document: v2
    Contact: api.keap@thryv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateAffiliateRequest(BaseModel):
    """
    CreateAffiliateRequest
    """ # noqa: E501
    code: StrictStr = Field(description="The Affiliate code which have some validations. 1. The code should not have white spaces 2. The code should starts with letters 3. The code minimum 4 characters length")
    status: Optional[StrictStr] = Field(default='INACTIVE', description="The Affiliate Status")
    name: Optional[StrictStr] = Field(default=None, description="The Affiliate name will be derived from the Contact, when not explicitly provided")
    contact_id: StrictStr = Field(description="The contactId identifier , Must be a positive number")
    parent_affiliate_id: Optional[StrictStr] = Field(default=None, description="The Parent Affiliate Id")
    notify_on_sale: Optional[StrictBool] = Field(default=None, description="Whether to notify on sale events")
    notify_on_lead: Optional[StrictBool] = Field(default=None, description="Whether to notify on lead events")
    track_leads_days: Optional[StrictInt] = Field(default=None, description="Number of days to track leads")
    password: Optional[StrictStr] = Field(default=None, description="Affiliate portal password")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["code", "status", "name", "contact_id", "parent_affiliate_id", "notify_on_sale", "notify_on_lead", "track_leads_days", "password"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'INACTIVE']):
            raise ValueError("must be one of enum values ('ACTIVE', 'INACTIVE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAffiliateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAffiliateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "status": obj.get("status") if obj.get("status") is not None else 'INACTIVE',
            "name": obj.get("name"),
            "contact_id": obj.get("contact_id"),
            "parent_affiliate_id": obj.get("parent_affiliate_id"),
            "notify_on_sale": obj.get("notify_on_sale"),
            "notify_on_lead": obj.get("notify_on_lead"),
            "track_leads_days": obj.get("track_leads_days"),
            "password": obj.get("password")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


