# coding: utf-8

"""
    Keap API

    Keap Public API Documentation

    The version of the OpenAPI document: v2
    Contact: api.keap@thryv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from keap_core_v2_client.models.address import Address
from keap_core_v2_client.models.email_address import EmailAddress
from keap_core_v2_client.models.fax_number import FaxNumber
from keap_core_v2_client.models.phone_number import PhoneNumber
from keap_core_v2_client.models.social_account import SocialAccount
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    A user in the system
    """ # noqa: E501
    address: Optional[Address] = Field(default=None, description="The user's address")
    title: Optional[StrictStr] = Field(default=None, description="The user's job title")
    website: Optional[StrictStr] = Field(default=None, description="The user's website URL")
    partner: Optional[StrictBool] = Field(default=None, description="Whether the user is a partner")
    admin: Optional[StrictBool] = Field(default=None, description="Whether the user is an admin")
    status: Optional[StrictStr] = Field(default=None, description="The user's status")
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the user")
    global_user_id: Optional[StrictStr] = Field(default=None, description="The global user identifier across tenants")
    keap_id: Optional[StrictStr] = Field(default=None, description="The Keap ID of the user")
    given_name: Optional[StrictStr] = Field(default=None, description="The user's first name")
    family_name: Optional[StrictStr] = Field(default=None, description="The user's last name")
    phone_numbers: Optional[List[PhoneNumber]] = Field(default=None, description="List of user's phone numbers")
    fax_numbers: Optional[List[FaxNumber]] = Field(default=None, description="List of user's fax numbers")
    email_addresses: Optional[List[EmailAddress]] = Field(default=None, description="List of user's email addresses")
    social_accounts: Optional[List[SocialAccount]] = Field(default=None, description="List of user's social media accounts")
    company_name: Optional[StrictStr] = Field(default=None, description="The user's company name")
    created_by: Optional[StrictInt] = Field(default=None, description="ID of the user who created this user")
    create_time: Optional[datetime] = Field(default=None, description="When the user was created, in ISO-8601 format")
    updated_by: Optional[StrictInt] = Field(default=None, description="ID of the user who last updated this user")
    update_time: Optional[datetime] = Field(default=None, description="When the user was last updated, in ISO-8601 format")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["address", "title", "website", "partner", "admin", "status", "id", "global_user_id", "keap_id", "given_name", "family_name", "phone_numbers", "fax_numbers", "email_addresses", "social_accounts", "company_name", "created_by", "create_time", "updated_by", "update_time"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'INVITED', 'INACTIVE', 'NOT_A_USER']):
            raise ValueError("must be one of enum values ('ACTIVE', 'INVITED', 'INACTIVE', 'NOT_A_USER')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in phone_numbers (list)
        _items = []
        if self.phone_numbers:
            for _item_phone_numbers in self.phone_numbers:
                if _item_phone_numbers:
                    _items.append(_item_phone_numbers.to_dict())
            _dict['phone_numbers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fax_numbers (list)
        _items = []
        if self.fax_numbers:
            for _item_fax_numbers in self.fax_numbers:
                if _item_fax_numbers:
                    _items.append(_item_fax_numbers.to_dict())
            _dict['fax_numbers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in email_addresses (list)
        _items = []
        if self.email_addresses:
            for _item_email_addresses in self.email_addresses:
                if _item_email_addresses:
                    _items.append(_item_email_addresses.to_dict())
            _dict['email_addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in social_accounts (list)
        _items = []
        if self.social_accounts:
            for _item_social_accounts in self.social_accounts:
                if _item_social_accounts:
                    _items.append(_item_social_accounts.to_dict())
            _dict['social_accounts'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": Address.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "title": obj.get("title"),
            "website": obj.get("website"),
            "partner": obj.get("partner"),
            "admin": obj.get("admin"),
            "status": obj.get("status"),
            "id": obj.get("id"),
            "global_user_id": obj.get("global_user_id"),
            "keap_id": obj.get("keap_id"),
            "given_name": obj.get("given_name"),
            "family_name": obj.get("family_name"),
            "phone_numbers": [PhoneNumber.from_dict(_item) for _item in obj["phone_numbers"]] if obj.get("phone_numbers") is not None else None,
            "fax_numbers": [FaxNumber.from_dict(_item) for _item in obj["fax_numbers"]] if obj.get("fax_numbers") is not None else None,
            "email_addresses": [EmailAddress.from_dict(_item) for _item in obj["email_addresses"]] if obj.get("email_addresses") is not None else None,
            "social_accounts": [SocialAccount.from_dict(_item) for _item in obj["social_accounts"]] if obj.get("social_accounts") is not None else None,
            "company_name": obj.get("company_name"),
            "created_by": obj.get("created_by"),
            "create_time": obj.get("create_time"),
            "updated_by": obj.get("updated_by"),
            "update_time": obj.get("update_time")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


