/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceCommissionProgram } from '../models/ResourceCommissionProgram';
import { HttpFile } from '../http/http';

export class AffiliateProgramResource {
    /**
    * The program resource identifier
    */
    'id'?: string;
    /**
    * The program resource title
    */
    'title'?: string;
    /**
    * The type of resource
    */
    'type'?: AffiliateProgramResourceTypeEnum;
    /**
    * The resource notes.
    */
    'notes'?: string;
    /**
    * The URL to the resource.
    */
    'url'?: string;
    /**
    * The order which the resource to be displayed. Minimum value is 0. Lower values indicate higher priority.
    */
    'order'?: number;
    /**
    * The contents of the PAGE or EMAIL. In HTML format.
    */
    'contentHtml'?: string;
    /**
    * The width of the page for PAGE types, in pixels.
    */
    'pageWidth'?: number;
    /**
    * The height of the page for PAGE types, in pixels.
    */
    'pageHeight'?: number;
    /**
    * A list of commission programs using this resource.
    */
    'commissionPrograms'?: Array<ResourceCommissionProgram>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AffiliateProgramResourceTypeEnum",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "contentHtml",
            "baseName": "content_html",
            "type": "string",
            "format": ""
        },
        {
            "name": "pageWidth",
            "baseName": "page_width",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pageHeight",
            "baseName": "page_height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "commissionPrograms",
            "baseName": "commission_programs",
            "type": "Array<ResourceCommissionProgram>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AffiliateProgramResource.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AffiliateProgramResourceTypeEnum {
    Email = 'EMAIL',
    Banner = 'BANNER',
    Page = 'PAGE'
}

