/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AffiliateLink {
    /**
    * Affiliate link ID
    */
    'id'?: string;
    /**
    * Link name
    */
    'name'?: string;
    /**
    * Associated affiliate ID
    */
    'affiliateId'?: string;
    /**
    * URL code for tracking
    */
    'localUrlCode'?: string;
    /**
    * Destination URL
    */
    'redirectUrl'?: string;
    /**
    * Associated program IDs
    */
    'programIds'?: Array<string>;
    /**
    * Date link was created (ISO-8601)
    */
    'dateCreated'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "affiliateId",
            "baseName": "affiliate_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "localUrlCode",
            "baseName": "local_url_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirectUrl",
            "baseName": "redirect_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "programIds",
            "baseName": "program_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AffiliateLink.attributeTypeMap;
    }

    public constructor() {
    }
}
