/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomFieldValueObject } from '../models/CustomFieldValueObject';
import { HttpFile } from '../http/http';

export class CreateNoteRequest {
    /**
    * A value for either `title` or `type` is required.
    */
    'title'?: string;
    /**
    * Note content
    */
    'text'?: string;
    /**
    * A value for either `title` or `type` is required. The value may be one of `Appointment`, `Call`, `Email`, `Fax`, `Letter` or `Other` in Keap Max/Pro, or an admin-configured value in Classic.
    */
    'type'?: string;
    /**
    * ID of user creating the note
    */
    'userId': string;
    /**
    * Whether to pin this note
    */
    'isPinned'?: boolean;
    /**
    * Custom field values for the note. An empty array resets all custom fields to their defaults.
    */
    'customFields'?: Array<CustomFieldValueObject>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPinned",
            "baseName": "is_pinned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<CustomFieldValueObject>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNoteRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
