/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CustomFieldTab {
    /**
    * The unique identifier of the custom field tab
    */
    'id'?: string;
    /**
    * The name of the custom field tab
    */
    'name'?: string;
    /**
    * The display order of the tab
    */
    'order'?: number;
    /**
    * The record type this tab belongs to (e.g., CONTACT, COMPANY, OPPORTUNITY, REFERRAL_PARTNER, ORDER, SUBSCRIPTION, TASK_NOTE_APPOINTMENT)
    */
    'recordType'?: CustomFieldTabRecordTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "recordType",
            "baseName": "record_type",
            "type": "CustomFieldTabRecordTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomFieldTab.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CustomFieldTabRecordTypeEnum {
    Contact = 'CONTACT',
    ReferralPartner = 'REFERRAL_PARTNER',
    Opportunity = 'OPPORTUNITY',
    TaskNoteAppointment = 'TASK_NOTE_APPOINTMENT',
    Company = 'COMPANY',
    Order = 'ORDER',
    Subscription = 'SUBSCRIPTION'
}

