/**
 * Keap REST API
 * Keap REST Core Service
 *
 * OpenAPI spec version: 2.70.0.809589
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DisplayGroup } from '../models/DisplayGroup';
import { HttpFile } from '../http/http';

/**
* A display form for a sales pipeline
*/
export class DisplayForm {
    /**
    * Groups of properties to display on the form.
    */
    'groups'?: Array<DisplayGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<DisplayGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DisplayForm.attributeTypeMap;
    }

    public constructor() {
    }
}
