/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LeadSource {
    /**
    * The unique identifier for this lead source
    */
    'id'?: string;
    /**
    * The name of the lead source
    */
    'name'?: string;
    /**
    * The description of the lead source
    */
    'description'?: string;
    /**
    * The vendor of the lead source
    */
    'vendor'?: string;
    /**
    * The medium of the lead source
    */
    'medium'?: string;
    /**
    * The message/content of the lead source
    */
    'message'?: string;
    /**
    * The status of the lead source
    */
    'status'?: LeadSourceStatusEnum;
    /**
    * The ID of the category that the lead source belongs to
    */
    'leadSourceCategoryId'?: string;
    /**
    * The time that this lead source started
    */
    'startTime'?: Date;
    /**
    * The time that this lead source will end
    */
    'endTime'?: Date;
    /**
    * The time that this lead source was created
    */
    'createTime'?: Date;
    /**
    * The time that this lead source was last updated
    */
    'updateTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "vendor",
            "baseName": "vendor",
            "type": "string",
            "format": ""
        },
        {
            "name": "medium",
            "baseName": "medium",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "LeadSourceStatusEnum",
            "format": ""
        },
        {
            "name": "leadSourceCategoryId",
            "baseName": "lead_source_category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return LeadSource.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum LeadSourceStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE'
}

