/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListMerchantAccountResponse } from '../models/ListMerchantAccountResponse';
import { HttpFile } from '../http/http';

export class ListMerchantsResponse {
    'defaultMerchantAccountId'?: string;
    'merchantAccounts'?: Array<ListMerchantAccountResponse>;
    'nextPageToken'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultMerchantAccountId",
            "baseName": "default_merchant_account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "merchantAccounts",
            "baseName": "merchant_accounts",
            "type": "Array<ListMerchantAccountResponse>",
            "format": ""
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListMerchantsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
