/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListOption {
    /**
    * The unique id of this option’s item value.
    */
    'itemId'?: string;
    /**
    * The displayable name of the option item.
    */
    'itemLabel'?: string;
    /**
    * An internal code (e.g. sku) to associate the item option.
    */
    'itemCode'?: string;
    /**
    * The order in which this item will be displayed among other items. Minimum is 0. Lower values indicate higher priority in order.
    */
    'itemDisplayOrder'?: number;
    /**
    * An amount to adjust to the product price is selected. Negative value indicates subtraction from price.
    */
    'priceAdjustment'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "itemId",
            "baseName": "item_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemLabel",
            "baseName": "item_label",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemCode",
            "baseName": "item_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemDisplayOrder",
            "baseName": "item_display_order",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "priceAdjustment",
            "baseName": "price_adjustment",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return ListOption.attributeTypeMap;
    }

    public constructor() {
    }
}
