/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Historical record of an opportunity moving from one pipeline stage to another
*/
export class OpportunityStageMove {
    /**
    * Unique ID of this stage-move record
    */
    'id'?: string;
    /**
    * ID of the opportunity that was moved
    */
    'opportunityId'?: string;
    /**
    * Date-time when the move occurred (ISO-8601 UTC)
    */
    'moveTime'?: string;
    /**
    * ID of the stage moved FROM. 0 = no previous stage (first move)
    */
    'moveFromStageId'?: string;
    /**
    * ID of the stage moved TO
    */
    'moveToStageId'?: string;
    /**
    * Date-time of the previous stage-move (ISO-8601 UTC). Null if first move.
    */
    'prevStageMoveTime'?: string;
    /**
    * ID of the user associated with this move
    */
    'userId'?: string;
    /**
    * ID of the user who created this record
    */
    'createdBy'?: string;
    /**
    * Date-time this record was created (ISO-8601 UTC)
    */
    'createTime'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "opportunityId",
            "baseName": "opportunity_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "moveTime",
            "baseName": "move_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "moveFromStageId",
            "baseName": "move_from_stage_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "moveToStageId",
            "baseName": "move_to_stage_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevStageMoveTime",
            "baseName": "prev_stage_move_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "created_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OpportunityStageMove.attributeTypeMap;
    }

    public constructor() {
    }
}
