/**
 * Keap REST API
 * Keap REST Core Service
 *
 * OpenAPI spec version: 2.70.0.809589
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Enum representing the display types for a boolean custom field.
*/
export enum PipelineCustomFieldBooleanDisplayType {
    Radio = 'RADIO',
    Checkbox = 'CHECKBOX',
    Toggle = 'TOGGLE',
    ToggleButton = 'TOGGLE_BUTTON'
}
