/**
 * Keap REST API
 * Keap REST Core Service
 *
 * OpenAPI spec version: 2.70.0.812056
 * Contact: api@keap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PipelineCustomFieldDurationOptionsDurationUnit } from '../models/PipelineCustomFieldDurationOptionsDurationUnit';
import { HttpFile } from '../http/http';

/**
* Class representing display options for a custom field with duration type.
*/
export class PipelineCustomFieldDurationDisplayOptions {
    /**
    * The list of duration units for the custom field. This field is optional.
    */
    'durationUnits'?: Array<PipelineCustomFieldDurationOptionsDurationUnit>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "durationUnits",
            "baseName": "duration_units",
            "type": "Array<PipelineCustomFieldDurationOptionsDurationUnit>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PipelineCustomFieldDurationDisplayOptions.attributeTypeMap;
    }

    public constructor() {
    }
}
