/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrencyValue } from '../models/CurrencyValue';
import { HttpFile } from '../http/http';

export class ProductInterest {
    /**
    * The product interest ID
    */
    'id'?: string;
    /**
    * The product interest type
    */
    'type'?: ProductInterestTypeEnum;
    /**
    * The quantity of product.
    */
    'quantity'?: number;
    /**
    * The price per unit of the product.
    */
    'price'?: CurrencyValue;
    /**
    * The interest ID
    */
    'interestId'?: string;
    /**
    * The percent to discount the product. Percent represented in a whole number, for example 10 is 10%
    */
    'discountPercent'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductInterestTypeEnum",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "CurrencyValue",
            "format": ""
        },
        {
            "name": "interestId",
            "baseName": "interest_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "discountPercent",
            "baseName": "discount_percent",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ProductInterest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductInterestTypeEnum {
    Product = 'PRODUCT',
    SubscriptionPlan = 'SUBSCRIPTION_PLAN'
}

