/**
 * Keap API
 * Keap Public API Documentation
 *
 * OpenAPI spec version: v2
 * Contact: api.keap@thryv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Company } from '../models/Company';
import { HttpFile } from '../http/http';

export class TaggedCompany {
    /**
    * The company the tag is applied to
    */
    'company'?: Company;
    /**
    * The time the tag was applied to the company, in ISO 8601 format.
    */
    'appliedTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "company",
            "baseName": "company",
            "type": "Company",
            "format": ""
        },
        {
            "name": "appliedTime",
            "baseName": "applied_time",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return TaggedCompany.attributeTypeMap;
    }

    public constructor() {
    }
}
