/*
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// ChecklistItem
    /// </summary>
    [DataContract(Name = "ChecklistItem")]
    public partial class ChecklistItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChecklistItem" /> class.
        /// </summary>
        /// <param name="id">Checklist item ID.</param>
        /// <param name="description">Item description.</param>
        /// <param name="required">Whether item is required.</param>
        /// <param name="order">Display order.</param>
        public ChecklistItem(string id = default, string description = default, bool required = default, int order = default)
        {
            this.Id = id;
            this.Description = description;
            this.Required = required;
            this.Order = order;
        }

        /// <summary>
        /// Checklist item ID
        /// </summary>
        /// <value>Checklist item ID</value>
        /*
        <example>101</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Item description
        /// </summary>
        /// <value>Item description</value>
        /*
        <example>Send proposal document</example>
        */
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Whether item is required
        /// </summary>
        /// <value>Whether item is required</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "required", EmitDefaultValue = true)]
        public bool Required { get; set; }

        /// <summary>
        /// Display order
        /// </summary>
        /// <value>Display order</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public int Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChecklistItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
