/*
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// task
    /// </summary>
    [DataContract(Name = "CreateUpdateTaskRequest")]
    public partial class CreateUpdateTaskRequest : IValidatableObject
    {
        /// <summary>
        /// Task priority
        /// </summary>
        /// <value>Task priority</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PriorityEnum
        {
            /// <summary>
            /// Enum CRITICAL for value: CRITICAL
            /// </summary>
            [EnumMember(Value = "CRITICAL")]
            CRITICAL = 1,

            /// <summary>
            /// Enum ESSENTIAL for value: ESSENTIAL
            /// </summary>
            [EnumMember(Value = "ESSENTIAL")]
            ESSENTIAL = 2,

            /// <summary>
            /// Enum NONESSENTIAL for value: NONESSENTIAL
            /// </summary>
            [EnumMember(Value = "NONESSENTIAL")]
            NONESSENTIAL = 3
        }

        /// <summary>
        /// Task priority
        /// </summary>
        /// <value>Task priority</value>
        /*
        <example>ESSENTIAL</example>
        */
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public PriorityEnum? Priority { get; set; }
        /// <summary>
        /// Value in minutes before start_date to show pop-up reminder.
        /// </summary>
        /// <value>Value in minutes before start_date to show pop-up reminder.</value>
        public enum RemindTimeMinsEnum
        {
            /// <summary>
            /// Enum NUMBER_5 for value: 5
            /// </summary>
            NUMBER_5 = 5,

            /// <summary>
            /// Enum NUMBER_10 for value: 10
            /// </summary>
            NUMBER_10 = 10,

            /// <summary>
            /// Enum NUMBER_15 for value: 15
            /// </summary>
            NUMBER_15 = 15,

            /// <summary>
            /// Enum NUMBER_30 for value: 30
            /// </summary>
            NUMBER_30 = 30,

            /// <summary>
            /// Enum NUMBER_60 for value: 60
            /// </summary>
            NUMBER_60 = 60,

            /// <summary>
            /// Enum NUMBER_120 for value: 120
            /// </summary>
            NUMBER_120 = 120,

            /// <summary>
            /// Enum NUMBER_240 for value: 240
            /// </summary>
            NUMBER_240 = 240,

            /// <summary>
            /// Enum NUMBER_480 for value: 480
            /// </summary>
            NUMBER_480 = 480,

            /// <summary>
            /// Enum NUMBER_1440 for value: 1440
            /// </summary>
            NUMBER_1440 = 1440,

            /// <summary>
            /// Enum NUMBER_2880 for value: 2880
            /// </summary>
            NUMBER_2880 = 2880
        }

        /// <summary>
        /// Value in minutes before start_date to show pop-up reminder.
        /// </summary>
        /// <value>Value in minutes before start_date to show pop-up reminder.</value>
        /*
        <example>30</example>
        */
        [DataMember(Name = "remind_time_mins", EmitDefaultValue = false)]
        public RemindTimeMinsEnum? RemindTimeMins { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateUpdateTaskRequest" /> class.
        /// </summary>
        /// <param name="title">Task title.</param>
        /// <param name="description">Task description.</param>
        /// <param name="type">Task type.</param>
        /// <param name="priority">Task priority.</param>
        /// <param name="completed">Whether task is completed.</param>
        /// <param name="completionTime">Completion timestamp (ISO-8601).</param>
        /// <param name="dueTime">Due date/time (ISO-8601).</param>
        /// <param name="remindTimeMins">Value in minutes before start_date to show pop-up reminder..</param>
        /// <param name="assignedToUserId">Assigned user ID.</param>
        /// <param name="contactId">Associated contact ID.</param>
        /// <param name="customFields">Custom field values for the task. An empty array resets all custom fields to their defaults..</param>
        public CreateUpdateTaskRequest(string title = default, string description = default, string type = default, PriorityEnum? priority = default, bool completed = default, string completionTime = default, string dueTime = default, RemindTimeMinsEnum? remindTimeMins = default, string assignedToUserId = default, string contactId = default, List<CustomFieldValueObject> customFields = default)
        {
            this.Title = title;
            this.Description = description;
            this.Type = type;
            this.Priority = priority;
            this.Completed = completed;
            this.CompletionTime = completionTime;
            this.DueTime = dueTime;
            this.RemindTimeMins = remindTimeMins;
            this.AssignedToUserId = assignedToUserId;
            this.ContactId = contactId;
            this.CustomFields = customFields;
        }

        /// <summary>
        /// Task title
        /// </summary>
        /// <value>Task title</value>
        /*
        <example>Follow up on proposal</example>
        */
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Task description
        /// </summary>
        /// <value>Task description</value>
        /*
        <example>Review client feedback</example>
        */
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Task type
        /// </summary>
        /// <value>Task type</value>
        /*
        <example>CALL</example>
        */
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Whether task is completed
        /// </summary>
        /// <value>Whether task is completed</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "completed", EmitDefaultValue = true)]
        public bool Completed { get; set; }

        /// <summary>
        /// Completion timestamp (ISO-8601)
        /// </summary>
        /// <value>Completion timestamp (ISO-8601)</value>
        /*
        <example>2024-03-20T14:00:00Z</example>
        */
        [DataMember(Name = "completion_time", EmitDefaultValue = false)]
        public string CompletionTime { get; set; }

        /// <summary>
        /// Due date/time (ISO-8601)
        /// </summary>
        /// <value>Due date/time (ISO-8601)</value>
        /*
        <example>2024-03-18T17:00:00Z</example>
        */
        [DataMember(Name = "due_time", EmitDefaultValue = false)]
        public string DueTime { get; set; }

        /// <summary>
        /// Assigned user ID
        /// </summary>
        /// <value>Assigned user ID</value>
        /*
        <example>456</example>
        */
        [DataMember(Name = "assigned_to_user_id", EmitDefaultValue = false)]
        public string AssignedToUserId { get; set; }

        /// <summary>
        /// Associated contact ID
        /// </summary>
        /// <value>Associated contact ID</value>
        /*
        <example>1001</example>
        */
        [DataMember(Name = "contact_id", EmitDefaultValue = false)]
        public string ContactId { get; set; }

        /// <summary>
        /// Custom field values for the task. An empty array resets all custom fields to their defaults.
        /// </summary>
        /// <value>Custom field values for the task. An empty array resets all custom fields to their defaults.</value>
        /*
        <example>[{id&#x3D;1, content&#x3D;Red}]</example>
        */
        [DataMember(Name = "custom_fields", EmitDefaultValue = false)]
        public List<CustomFieldValueObject> CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateUpdateTaskRequest {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Completed: ").Append(Completed).Append("\n");
            sb.Append("  CompletionTime: ").Append(CompletionTime).Append("\n");
            sb.Append("  DueTime: ").Append(DueTime).Append("\n");
            sb.Append("  RemindTimeMins: ").Append(RemindTimeMins).Append("\n");
            sb.Append("  AssignedToUserId: ").Append(AssignedToUserId).Append("\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
