/*
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// ListAssignedProductsResponse
    /// </summary>
    [DataContract(Name = "ListAssignedProductsResponse")]
    public partial class ListAssignedProductsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListAssignedProductsResponse" /> class.
        /// </summary>
        /// <param name="assignedProductCategories">assignedProductCategories.</param>
        /// <param name="nextPageToken">nextPageToken.</param>
        public ListAssignedProductsResponse(List<AssignedProducts> assignedProductCategories = default, string nextPageToken = default)
        {
            this.AssignedProductCategories = assignedProductCategories;
            this.NextPageToken = nextPageToken;
        }

        /// <summary>
        /// Gets or Sets AssignedProductCategories
        /// </summary>
        [DataMember(Name = "assigned_product_categories", EmitDefaultValue = false)]
        public List<AssignedProducts> AssignedProductCategories { get; set; }

        /// <summary>
        /// Gets or Sets NextPageToken
        /// </summary>
        [DataMember(Name = "next_page_token", EmitDefaultValue = false)]
        public string NextPageToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListAssignedProductsResponse {\n");
            sb.Append("  AssignedProductCategories: ").Append(AssignedProductCategories).Append("\n");
            sb.Append("  NextPageToken: ").Append(NextPageToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
