/*
 * Keap REST API
 *
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.812056
 * Contact: api@keap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// Class representing display options for a custom field with duration type.
    /// </summary>
    [DataContract(Name = "PipelineCustomFieldDurationDisplayOptions")]
    public partial class PipelineCustomFieldDurationDisplayOptions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PipelineCustomFieldDurationDisplayOptions" /> class.
        /// </summary>
        /// <param name="durationUnits">The list of duration units for the custom field. This field is optional..</param>
        public PipelineCustomFieldDurationDisplayOptions(List<PipelineCustomFieldDurationOptionsDurationUnit> durationUnits = default)
        {
            this.DurationUnits = durationUnits;
        }

        /// <summary>
        /// The list of duration units for the custom field. This field is optional.
        /// </summary>
        /// <value>The list of duration units for the custom field. This field is optional.</value>
        [DataMember(Name = "duration_units", EmitDefaultValue = false)]
        public List<PipelineCustomFieldDurationOptionsDurationUnit> DurationUnits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PipelineCustomFieldDurationDisplayOptions {\n");
            sb.Append("  DurationUnits: ").Append(DurationUnits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
