/*
 * Keap REST API
 *
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.809589
 * Contact: api@keap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// Enum representing the types of size validation for custom fields.
    /// </summary>
    /// <value>Enum representing the types of size validation for custom fields.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PipelineCustomFieldSizeValidationType
    {
        /// <summary>
        /// Enum MIN for value: MIN
        /// </summary>
        [EnumMember(Value = "MIN")]
        MIN = 1,

        /// <summary>
        /// Enum MAX for value: MAX
        /// </summary>
        [EnumMember(Value = "MAX")]
        MAX = 2
    }

}
