/*
 * Keap REST API
 *
 * Keap REST Core Service
 *
 * The version of the OpenAPI document: 2.70.0.809589
 * Contact: api@keap.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// Represents a list of custom fields in the system.
    /// </summary>
    [DataContract(Name = "PipelineCustomFields")]
    public partial class PipelineCustomFields : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PipelineCustomFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PipelineCustomFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PipelineCustomFields" /> class.
        /// </summary>
        /// <param name="customFields">The list of custom fields. (required).</param>
        public PipelineCustomFields(List<PipelineCustomField> customFields = default)
        {
            // to ensure "customFields" is required (not null)
            if (customFields == null)
            {
                throw new ArgumentNullException("customFields is a required property for PipelineCustomFields and cannot be null");
            }
            this.CustomFields = customFields;
        }

        /// <summary>
        /// The list of custom fields.
        /// </summary>
        /// <value>The list of custom fields.</value>
        [DataMember(Name = "custom_fields", IsRequired = true, EmitDefaultValue = true)]
        public List<PipelineCustomField> CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PipelineCustomFields {\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
