/*
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// RestCreatePaymentRequest
    /// </summary>
    [DataContract(Name = "RestCreatePaymentRequest")]
    public partial class RestCreatePaymentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RestCreatePaymentRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RestCreatePaymentRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RestCreatePaymentRequest" /> class.
        /// </summary>
        /// <param name="notes">The notes for this payment..</param>
        /// <param name="paymentMethodId">The payment method id to charge immediately against this order. At least one of payment_method_id or payment_method_type is required. If payment_method_id is provided, payment_method_type is ignored. Omit if you want to add a payment record instead..</param>
        /// <param name="paymentMethodType">The manual payment method type for manually recording a payment. At least one of payment_method_id or payment_method_type is required. Ignored if payment_method_id is provided. Value must exactly match one of the Manual Payment Types configured for your application under Ecommerce Settings &gt; Orders (e.g. &#39;Credit Card (Manual)&#39;, &#39;Check&#39;, &#39;Cash&#39;, &#39;Money Order&#39;, &#39;Adjustment&#39;); unrecognized values will be rejected. Add custom types there if the one you need isn&#39;t listed..</param>
        /// <param name="paymentTime">The date and time of payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z).</param>
        /// <param name="paymentAmount">The amount to pay. Must not exceed the current balance of the order. Must be greater than 0 if charging with a payment_method_id (required).</param>
        /// <param name="applyToCommissions">Whether to apply this payment to commissions. (required).</param>
        /// <param name="externalSource">The external source type of this payment..</param>
        /// <param name="externalSourceValue">The external source value of this payment..</param>
        /// <param name="externalStatusValue">The external status value of this payment..</param>
        /// <param name="externalCreateTime">The external creation timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z).</param>
        /// <param name="externalUpdateTime">The external update timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z).</param>
        /// <param name="externalCreateUser">The user who created this payment externally..</param>
        public RestCreatePaymentRequest(string notes = default, string paymentMethodId = default, string paymentMethodType = default, DateTime paymentTime = default, double paymentAmount = default, bool applyToCommissions = default, string externalSource = default, string externalSourceValue = default, string externalStatusValue = default, DateTime externalCreateTime = default, DateTime externalUpdateTime = default, string externalCreateUser = default)
        {
            this.PaymentAmount = paymentAmount;
            this.ApplyToCommissions = applyToCommissions;
            this.Notes = notes;
            this.PaymentMethodId = paymentMethodId;
            this.PaymentMethodType = paymentMethodType;
            this.PaymentTime = paymentTime;
            this.ExternalSource = externalSource;
            this.ExternalSourceValue = externalSourceValue;
            this.ExternalStatusValue = externalStatusValue;
            this.ExternalCreateTime = externalCreateTime;
            this.ExternalUpdateTime = externalUpdateTime;
            this.ExternalCreateUser = externalCreateUser;
        }

        /// <summary>
        /// The notes for this payment.
        /// </summary>
        /// <value>The notes for this payment.</value>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        public string Notes { get; set; }

        /// <summary>
        /// The payment method id to charge immediately against this order. At least one of payment_method_id or payment_method_type is required. If payment_method_id is provided, payment_method_type is ignored. Omit if you want to add a payment record instead.
        /// </summary>
        /// <value>The payment method id to charge immediately against this order. At least one of payment_method_id or payment_method_type is required. If payment_method_id is provided, payment_method_type is ignored. Omit if you want to add a payment record instead.</value>
        [DataMember(Name = "payment_method_id", EmitDefaultValue = false)]
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// The manual payment method type for manually recording a payment. At least one of payment_method_id or payment_method_type is required. Ignored if payment_method_id is provided. Value must exactly match one of the Manual Payment Types configured for your application under Ecommerce Settings &gt; Orders (e.g. &#39;Credit Card (Manual)&#39;, &#39;Check&#39;, &#39;Cash&#39;, &#39;Money Order&#39;, &#39;Adjustment&#39;); unrecognized values will be rejected. Add custom types there if the one you need isn&#39;t listed.
        /// </summary>
        /// <value>The manual payment method type for manually recording a payment. At least one of payment_method_id or payment_method_type is required. Ignored if payment_method_id is provided. Value must exactly match one of the Manual Payment Types configured for your application under Ecommerce Settings &gt; Orders (e.g. &#39;Credit Card (Manual)&#39;, &#39;Check&#39;, &#39;Cash&#39;, &#39;Money Order&#39;, &#39;Adjustment&#39;); unrecognized values will be rejected. Add custom types there if the one you need isn&#39;t listed.</value>
        [DataMember(Name = "payment_method_type", EmitDefaultValue = false)]
        public string PaymentMethodType { get; set; }

        /// <summary>
        /// The date and time of payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
        /// </summary>
        /// <value>The date and time of payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</value>
        /*
        <example>2024-05-21T14:30:00Z</example>
        */
        [DataMember(Name = "payment_time", EmitDefaultValue = false)]
        public DateTime PaymentTime { get; set; }

        /// <summary>
        /// The amount to pay. Must not exceed the current balance of the order. Must be greater than 0 if charging with a payment_method_id
        /// </summary>
        /// <value>The amount to pay. Must not exceed the current balance of the order. Must be greater than 0 if charging with a payment_method_id</value>
        [DataMember(Name = "payment_amount", IsRequired = true, EmitDefaultValue = true)]
        public double PaymentAmount { get; set; }

        /// <summary>
        /// Whether to apply this payment to commissions.
        /// </summary>
        /// <value>Whether to apply this payment to commissions.</value>
        [DataMember(Name = "apply_to_commissions", IsRequired = true, EmitDefaultValue = true)]
        public bool ApplyToCommissions { get; set; }

        /// <summary>
        /// The external source type of this payment.
        /// </summary>
        /// <value>The external source type of this payment.</value>
        [DataMember(Name = "external_source", EmitDefaultValue = false)]
        public string ExternalSource { get; set; }

        /// <summary>
        /// The external source value of this payment.
        /// </summary>
        /// <value>The external source value of this payment.</value>
        [DataMember(Name = "external_source_value", EmitDefaultValue = false)]
        public string ExternalSourceValue { get; set; }

        /// <summary>
        /// The external status value of this payment.
        /// </summary>
        /// <value>The external status value of this payment.</value>
        [DataMember(Name = "external_status_value", EmitDefaultValue = false)]
        public string ExternalStatusValue { get; set; }

        /// <summary>
        /// The external creation timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
        /// </summary>
        /// <value>The external creation timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</value>
        /*
        <example>2024-05-21T14:30:00Z</example>
        */
        [DataMember(Name = "external_create_time", EmitDefaultValue = false)]
        public DateTime ExternalCreateTime { get; set; }

        /// <summary>
        /// The external update timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)
        /// </summary>
        /// <value>The external update timestamp of this payment. In ISO-8601 format (e.g. 2024-05-21T23:00:00Z)</value>
        /*
        <example>2024-05-21T14:30:00Z</example>
        */
        [DataMember(Name = "external_update_time", EmitDefaultValue = false)]
        public DateTime ExternalUpdateTime { get; set; }

        /// <summary>
        /// The user who created this payment externally.
        /// </summary>
        /// <value>The user who created this payment externally.</value>
        [DataMember(Name = "external_create_user", EmitDefaultValue = false)]
        public string ExternalCreateUser { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RestCreatePaymentRequest {\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  PaymentMethodId: ").Append(PaymentMethodId).Append("\n");
            sb.Append("  PaymentMethodType: ").Append(PaymentMethodType).Append("\n");
            sb.Append("  PaymentTime: ").Append(PaymentTime).Append("\n");
            sb.Append("  PaymentAmount: ").Append(PaymentAmount).Append("\n");
            sb.Append("  ApplyToCommissions: ").Append(ApplyToCommissions).Append("\n");
            sb.Append("  ExternalSource: ").Append(ExternalSource).Append("\n");
            sb.Append("  ExternalSourceValue: ").Append(ExternalSourceValue).Append("\n");
            sb.Append("  ExternalStatusValue: ").Append(ExternalStatusValue).Append("\n");
            sb.Append("  ExternalCreateTime: ").Append(ExternalCreateTime).Append("\n");
            sb.Append("  ExternalUpdateTime: ").Append(ExternalUpdateTime).Append("\n");
            sb.Append("  ExternalCreateUser: ").Append(ExternalCreateUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
