/*
 * Keap API
 *
 * Keap Public API Documentation
 *
 * The version of the OpenAPI document: v2
 * Contact: api.keap@thryv.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Keap.Core.V2.Client.OpenAPIDateConverter;

namespace Keap.Core.V2.Model
{
    /// <summary>
    /// Tag
    /// </summary>
    [DataContract(Name = "Tag")]
    public partial class Tag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Tag" /> class.
        /// </summary>
        /// <param name="id">The unique identifier for this tag.</param>
        /// <param name="name">The unique name of this tag.</param>
        /// <param name="description">A description of this tag.</param>
        /// <param name="category">The category this tag belongs to.</param>
        /// <param name="createTime">The time this tag was created, in ISO 8601 format.</param>
        /// <param name="updateTime">The time this tag was last updated, in ISO 8601 format.</param>
        public Tag(string id = default, string name = default, string description = default, CategoryReference category = default, DateTime createTime = default, DateTime updateTime = default)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.Category = category;
            this.CreateTime = createTime;
            this.UpdateTime = updateTime;
        }

        /// <summary>
        /// The unique identifier for this tag
        /// </summary>
        /// <value>The unique identifier for this tag</value>
        /*
        <example>123</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The unique name of this tag
        /// </summary>
        /// <value>The unique name of this tag</value>
        /*
        <example>VIP Customer</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// A description of this tag
        /// </summary>
        /// <value>A description of this tag</value>
        /*
        <example>High-value customers</example>
        */
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The category this tag belongs to
        /// </summary>
        /// <value>The category this tag belongs to</value>
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public CategoryReference Category { get; set; }

        /// <summary>
        /// The time this tag was created, in ISO 8601 format
        /// </summary>
        /// <value>The time this tag was created, in ISO 8601 format</value>
        /*
        <example>2024-01-10T08:00:00Z</example>
        */
        [DataMember(Name = "create_time", EmitDefaultValue = false)]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// The time this tag was last updated, in ISO 8601 format
        /// </summary>
        /// <value>The time this tag was last updated, in ISO 8601 format</value>
        /*
        <example>2024-03-15T10:30:00Z</example>
        */
        [DataMember(Name = "update_time", EmitDefaultValue = false)]
        public DateTime UpdateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Tag {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  UpdateTime: ").Append(UpdateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
