name: Publish Node Package to npmjs

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.release.tag_name }}
      url: "https://www.npmjs.com/package/keap-core-service-v2-sdk-ts/v/${{ github.event.release.tag_name }}"
  permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Javascript
      - name: Install Javascript dependencies
        working-directory: sdks/v2/javascript
        run: npm install

      - name: Publish Core Javascript package to npmjs
        run: npm publish --provenance --access public
        working-directory: sdks/v2/javascript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Typescript
      - name: Install Typescript dependencies
        working-directory: sdks/v2/typescript
        run: npm install

      - name: Publish Core Typescript package to npmjs
        run: npm publish --provenance --access public
        working-directory: sdks/v2/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
