name: Publish C# SDK to NuGet

on:
  release:
    types: [published]
        
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
        name: ${{ github.event.release.tag_name }}
        url: "https://www.nuget.org/packages/Keap.Core.V2/${{ github.event.release.tag_name }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore sdks/v2/csharp/Keap.Core.V2.sln

      - name: Pack NuGet package
        run: |
          VERSION=$(git describe --tags --abbrev=0)

          echo "Packaging version $VERSION"

          dotnet pack sdks/v2/csharp/Keap.Core.V2.sln \
            --configuration Release \
            --output ./nupkgs \
            -p:PackageVersion=$VERSION

      - name: Push package to NuGet
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
